<div class="t-c p-t20">
	<span class="app-box-android">
		<i></i>
		<img src="http://img1.ph.126.net/yoi0jh-ECCgc5C4WTrw_kQ==/1001487967154158891.png" alt="">
	</span>
	<div class="m-t10">
	</div>
	<p class="m-t15">
		<a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&amp;id=1806626&amp;pf=2&amp;cg=CA96B6HQND1&amp;sign=fb8572d4467c2c714945d0ad55090d53&amp;url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201206%2F15%2Fcom.rovio.angrybirdsseasons-240.apk" target="_self" class="btn-download-byandroid"></a>
	</p>
	<p class="m-t8">
		<a href="http://m.163.com/software/download?prod=3gmarket&amp;id=1806626&amp;pf=2&amp;cg=CA96B6HQND5&amp;sign=fb8572d4467c2c714945d0ad55090d53&amp;url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201206%2F15%2Fcom.rovio.angrybirdsseasons-240.apk" name="愤怒的小鸟夏日版(Angry Birds Seasons)" target="_self" class="btn-download-wdj2" onclick="return wdapi_apkdl_m(this,'163');"></a>
	</p>
	<p class="m-t8">
		<a href="javascript:void(0);" target="_self" class="f14px a-orange" id="btn-download-send">免费发送到手机</a>
	</p>
	<p class="m-t20 c-gray">大小：22.70M  </p>
	<p class="c-gray"> 版本：2.4.0 </p>
	<div class="m-t15">
		<a href="http://m.163.com/mobileapp/">
			<img src="http://img1.cache.netease.com/apps/v2/img/ad11.png" alt="">
		</a>
	</div>
</div>