<div class="t-c p-t20">
	<span class="app-box-android">
		<i></i>
		<img src="<?=$this->app->logo?>" alt="">
	</span>
	<div class="m-t10">
	</div>
	<p class="m-t15">
		<a href="/download/<?=$this->app->id?>" target="_self" class="btn-download-byandroid"></a>
	</p>
	<p class="m-t8">
		<a href="/download/<?=$this->app->id?>.html" name="<?=$this->app->name?>" target="_self" class="btn-download-wdj2" onclick="return wdapi_apkdl_m(this,'163');"></a>
	</p>
	<p class="m-t20 c-gray">大小：<?=$this->app->size?>  </p>
	<p class="c-gray"> 版本：<?=$this->app->version?> </p>
	<!--
	<div class="m-t15">
		<a href="http://m.163.com/mobileapp/">
			<img src="http://img1.cache.netease.com/apps/v2/img/ad11.png" alt="">
		</a>
	</div>
	-->
</div>