<div class="sect">
	<div class="crumb">当前位置：<a href="http://m.163.com/android" target="_self">
		Android首页</a> &gt; <a href="http://m.163.com/android/game/ca96b6hqnd/index.html" target="_self">休闲益智</a> &gt; 孢子战争(Spores &amp; Fighting)</div>
</div>

<div class="sect">
	<div class="arti">
	    <div class="arti-hd">
	        <div class="arti-hd-c"><div class="arti-hd-c-content"></div></div>
	        <span class="arti-hd-l"></span>
	        <span class="arti-hd-r"></span>
	    </div>
        <div class="arti-bd">
            <div class="arti-bd-content">
                <div class="clearfix">
                    <div class="sect-main-s">
                    	<div class="sect-main-s-inner p-t15">
                        	<h2><span class="f-h1">孢子战争(Spores &amp; Fighting)</span></h2>
                            <div class="m-t5 clearfix">
                            	<div class="fl-l m-r15">
                                	<span class="vote-column-s"><i style="width:0%"></i></span>
                                </div>
                            </div>
                                        
                            <div class="yui3-widget yui3-tabs">
                            	<div class="yui3-widget yui3-tabs">
                            		<div class="yui3-widget yui3-tabs">
                            			<div class="arti-s yui3-tabs-content" id="app-infos">
                                        	<div class="arti-s-hd">
                                                <ul class="tabs-2-list m-l10" id="yui_3_4_0_5_1339949668484_272">
                                                    <li id="yui_3_4_0_5_1339949668484_278"><span class="yui3-tabs-trigger yui3-tabs-trigger-selected" id="yui_3_4_0_5_1339949668484_277">简介</span></li>
                                                    <li id="yui_3_4_0_5_1339949668484_271"><span class="yui3-tabs-trigger" id="yui_3_4_0_5_1339949668484_270">参数</span></li>   
                                                </ul>
                                            </div>
                                            
                                            <div class="arti-s-bd p-v20 bg-solid-b">
                                                <div class="yui3-tabs-panel yui3-tabs-panel-selected">
                                                    <div class="f14px download-app-desc" id="app-desc" style="height: 75px; ">
                                                        <p class="c-orange">编辑点评：愤怒的小鸟最新夏日版。</p>                                                                                                                <p>
    欢迎来到美丽的亚特兰蒂斯的小猪世界（piglantis）！小鸟们又遇到了新的状况，在这水下仙境——尝试把小鸟弹射出去，看看会发生什么！ 在这神秘的热带礁湖王国，你有信心击败国王猪吗？一起探索水下遗址亚特兰蒂斯的小猪世界</p>
<p>
    （piglantis），挑战30个全新关卡！水物理特性一定让你爱不释手——提示：猪，下沉！这个夏天，尽情感受来自神秘的亚特兰蒂斯文明千年不息的流水声吧！</p>

                                                    </div>
                                                </div>
                                            <div class="yui3-tabs-panel">
                                                <table class="table-appinfo">
                                                    <tbody><tr>
                                                        <th>价格：</th>
                                                        <td>
                                                            <th>类别：</th><td>休闲益智 </td>
                                                        </tr>
                                                        <tr>
                                                            <th>大小：</th><td>22.70M</td>
                                                            <th>语言：</th><td>英文</td>
                                                        </tr>
                                                        <tr>
                                                             <th>版本：</th><td>2.4.0</td>
                                                        </tr>
                                                        <tr>
                                                            <th>开发者：</th><td>Rovio Mobile Ltd.</td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                                        
                                        <!-- begin: shots list -->
                            <div id="shotlist-container" class="yui3-imagelist m-v40 yui3-widget">
                            	<div class="yui3-imagelist-content">
                            		<div class="m-t15 pos-r">
                            			<div class="container-shot-list">
                            				<ul class="shot-list" id="shot-list">
                            					<li>
                            						<div class="box-download-shot"><img src="http://img6.ph.126.net/vJJF3L5XsFVuVkcqZZwsTg==/1303229142187968826.jpg" width="140" height="140" title="点击查看大图">
                            						</div>
                            					</li>
                            					<li>
                            						<div class="box-download-shot"><img src="http://img1.ph.126.net/m-UG1xAxHnzp0KCejefESQ==/1360650037436945971.jpg" width="140" height="140" title="点击查看大图">
                            						</div>
                            					</li>
                            					<li>
                            						<div class="box-download-shot"><img src="http://img3.ph.126.net/jtbk6BsKvGbTspL58rwa1g==/2509630892369843303.jpg" width="140" height="140" title="点击查看大图">
                            						</div>
                            					</li>
                            					<li>
                            						<div class="box-download-shot"><img src="http://img1.ph.126.net/X-IJ0lEMIWAIt851EjpC5w==/1324621240417975931.jpg" width="140" height="140" title="点击查看大图">
                            						</div>
                            					</li>
                            					<li>
                            						<div class="box-download-shot"><img src="http://img9.ph.126.net/ViVpAWMO8Beu6CQK5ldDAg==/2555792788550386719.jpg" width="140" height="140" title="点击查看大图">
                            						</div>
                            					</li>
                            				</ul>
                            			</div>
                            			<span class="yui3-imagelist-arrow-left yui3-imagelist-arrow-left-disabled"></span>
                            			<span class="yui3-imagelist-arrow-right "></span>
                            		</div>
                            	</div>
                            </div>
                                        
                            <div id="img-overlay" class="yui3-overlay-loading">
                            	<div style="width:600px; text-align:right; margin:0 auto">
                            		<span class="img_overlay_close"><span id="img_overlay_close"></span></span>
                            	</div>
                                <div id="img-overlay-center" style="position:relative;overflow: hidden;width: 100%; height:480px;">
                                    <div class="showImg_prev">
                                    	<a href="javascript:void(0);" target="_self" hidefocus="true" class="showImg_btn_prev" id="showImg_Prev"></a>
                                    </div>
                                    <div class="showImg_next">
                                    	<a href="javascript:void(0);" target="_self" hidefocus="true" class="showImg_btn_next" id="showImg_Next"></a>
                                   	</div>
                                    <div id="loadingGif" class="view-loading"></div>
                                    <table cellpadding="0" cellspacing="0">
                                    	<tbody><tr><td><img id="shown-img"></td></tr></tbody></table>
                                </div>
                                <div class="showImg_sel m-t20">
                                	<ul id="img-icon-list"></ul>
                                </div>
                            </div>
                        </div>
                    </div>
                                
                    <div class="sect-side-s">
                        <div class="t-c p-t20">
                            <span class="app-box-android">
                                <i></i>
                                <img src="./孢子战争(Spores &amp; Fighting)_休闲益智_Android首页_网易应用中心_files/2576903411803670004.png" alt="">
                            </span>
							<div class="m-t10"></div>
								<p class="m-t15"><a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&amp;id=2178022&amp;pf=2&amp;cg=CA96B6HQND1&amp;sign=0303b89d93ac2f4422b439d32897240d&amp;url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201206%2F11%2Fair.com.huale.SporesFighting-1002000.apk" target="_self" class="btn-download-byandroid"></a></p>
								<p class="m-t8"><a href="http://m.163.com/software/download?prod=3gmarket&amp;id=2178022&amp;pf=2&amp;cg=CA96B6HQND5&amp;sign=0303b89d93ac2f4422b439d32897240d&amp;url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201206%2F11%2Fair.com.huale.SporesFighting-1002000.apk" name="孢子战争(Spores &amp; Fighting)" target="_self" class="btn-download-wdj2" onclick="return wdapi_apkdl_m(this,'163');"></a></p>
                                <p class="c-gray"> 版本：v1.2 </p>
								<div class="m-t15">
									<a href="http://m.163.com/mobileapp/"><img src="./孢子战争(Spores &amp; Fighting)_休闲益智_Android首页_网易应用中心_files/ad11.png" alt=""></a>
								</div>
							</div>
                        </div>
                    </div>
                </div>
            </div>
                    
            <div class="arti-ft">
                <div class="arti-ft-c">
                    <div class="arti-ft-c-content"></div>
                </div>
                <span class="arti-ft-l"></span>
                <span class="arti-ft-r"></span>
            </div>
        </div>
    </div>