<div class="sect">
	<div class="crumb">当前位置：<a href="/android" target="_self">
		Android首页</a> &gt; <a href="/android/game/ca96b6hqnd/index.html" target="_self">休闲益智</a> &gt; 愤怒的小鸟夏日版(Angry Birds Seasons)
	</div>
</div>

<div class="sect">
	<div class="arti">
		<div class="arti-hd">
            <div class="arti-hd-c">
            	<div class="arti-hd-c-content"></div>
            </div>
            <span class="arti-hd-l"></span>
            <span class="arti-hd-r"></span>
        </div>

        <div class="arti-bd">
        	<div class="arti-bd-content">
        		<div class="clearfix">
        			<!--right begin-->
        			<div class="sect-main-s">
        				<?php echo $this->partial('app/right.phtml'); ?>
        			</div>
        			<!--right end->
        			<!--left begin-->
        			<div class="sect-side-s">
        				<?php echo $this->partial('app/left.phtml'); ?>
        			</div>
        			<!--left end-->
        		</div>
        	</div>
        </div>
	</div>
</div>