<?php 
	$this->headTitle("美眉安卓(Android)应用市场");
?>
<div class="content-box">
	<div class="column-lw-box">
		<div class="column-lw row-430">
			<div class="title-lw">
				<h1><div class="icon"></div>应用推荐</h1></div>
				<div class="box-lr20">
					<ul class="col2">
						<li class="icon"><img src="http://r.anfone.com/upload/icon/ICON_1337927424121.png" width="52" height="51">
						</li>
						<li class="name"><a href="/soft/34098.html">世纪佳缘</a></li>
						<li class="info"><i class="df-star star-3"></i> 3.86MB</li>
						<li class="comment">中国专业的严肃婚恋交友平台</li>
					</ul>
					<ul class="col2">
						<li class="icon"><img src="http://r.anfone.com/upload/icon/ICON_1339121088843.png" width="52" height="51"></li>
						<li class="name"><a href="/soft/35630.html">WiFi万能钥匙</a></li>
						<li class="info"><i class="df-star star-3"></i> 882.33KB</li>
						<li class="comment">随时随地轻松接入无线网络</li>
					</ul>
					<ul class="col2">
						<li class="icon"><img src="http://r.anfone.com/upload/icon/ICON_1334815875126.png" width="52" height="51"></li>
						<li class="name"><a href="/soft/29905.html">新浪微博</a></li>
						<li class="info"><i class="df-star star-5"></i> 4.79MB</li>
						<li class="comment">随时随地分享新鲜事儿</li>
					</ul>
					<ul class="col2">
						<li class="icon"><img src="http://r.anfone.com/upload/icon/ICON_1338261587776.png" width="52" height="51"></li>
						<li class="name"><a href="/soft/34355.html">GO联系人</a></li>
						<li class="info"><i class="df-star star-3"></i> 2.79MB</li>
						<li class="comment">功能强大的手机联系人增强应用</li>
					</ul>
					<ul class="col2">
						<li class="icon"><img src="http://r.anfone.com/upload/icon/ICON_1336988305154.png" width="52" height="51"></li>
						<li class="name"><a href="/soft/32644.html">米聊</a></li>
						<li class="info"><i class="df-star star-5"></i> 7.92MB</li>
						<li class="comment">小米出品的聊天交友工具</li>
					</ul>
					<ul class="col2">
						<li class="icon"><img src="http://r.anfone.com/upload/icon/ICON_1328605810462.png" width="52" height="51"></li>
						<li class="name"><a href="/soft/24963.html">裸眼3D手机播放器</a></li>
						<li class="info"><i class="df-star star-3"></i> 7.34MB</li>
						<li class="comment">强大的裸眼3D手机播放器</li>
					</ul>
					<ul class="col2">
						<li class="icon"><img src="http://r.anfone.com/upload/icon/ICON_1336988833090.png" width="52" height="51"></li>
						<li class="name"><a href="/soft/32646.html">360手机卫士</a></li>
						<li class="info"><i class="df-star star-5"></i> 4.65MB</li>
						<li class="comment">免费杀毒又安全</li>
					</ul>
					<ul class="col2">
						<li class="icon"><img src="http://r.anfone.com/upload/icon/ICON_1332379895703.png" width="52" height="51"></li>
						<li class="name"><a href="/soft/27403.html">Sexy Video-Natsuki</a></li>
						<li class="info"><i class="df-star star-3"></i> 1.93MB</li>
						<li class="comment">惹火影片和图片</li>
					</ul>
					<ul class="col2">
						<li class="icon"><img src="http://r.anfone.com/upload/icon/ICON_1338452921405.png" width="52" height="51"></li>
						<li class="name"><a href="/soft/34772.html">搜狗手机输入法</a></li>
						<li class="info"><i class="df-star star-3"></i> 5.63MB</li>
						<li class="comment">方便快捷，输入轻松</li>
					</ul>
					<ul class="col2">
						<li class="icon"><img src="http://r.anfone.com/upload/icon/ICON_1338782084159.png" width="52" height="51"></li>
						<li class="name"><a href="/soft/34855.html">第二号码</a></li>
						<li class="info"><i class="df-star star-3"></i> 1.75MB</li>
						<li class="comment">不换手机，实现一机多号</li>
					</ul>
				</div>
			</div>
		</div>

	<div class="column-r-box">
		<div class="column-r row-430">
			<ul class="title-r">
				<li>热门应用排行榜</li>
			</ul>
			<ul class="sort-r" id="app-tab_0">
			  <li><em class="top">01</em><a href="/soft/32195.html">手机买团购</a></li>
			  <li><em class="top">02</em><a href="/soft/22459.html">手机QQ2011</a></li>
			  <li><em class="top">03</em><a href="/soft/32488.html">微信</a></li>
			  <li><em>04</em><a href="/soft/33318.html">墨迹天气</a></li>
			  <li><em>05</em><a href="/soft/34772.html">搜狗手机输入法</a></li>
			  <li><em>06</em><a href="/soft/35454.html">谷歌地图</a></li>
			  <li><em>07</em><a href="/soft/27081.html">手机QQ2012</a></li>
			  <li><em>08</em><a href="/soft/35548.html">腾讯手机管家</a></li>
			  <li><em>09</em><a href="/soft/28573.html">Adobe Flash Player </a></li>
			  <li><em>10</em><a href="/soft/32646.html">360手机卫士</a></li>
			</ul>
		</div>
	</div>
	<div class="clear"></div>
</div>

<div class="content-box">
	<div class="column-lw-box">
		<div class="column-lw">
			<div class="row-430">
				<div class="title-lw">
					<h1><div class="icon"></div>游戏推荐</h1>
				</div>
				<div class="box-lr20">
					<ul class="col2">
						<li class="icon"><img src="http://r.anfone.com/upload/icon/ICON_1334815726535.png" width="52" height="51"></li>
						<li class="name"><a href="/soft/29904.html">极品飞车15:变速2</a></li>
						<li class="info"><i class="df-star star-5"></i> 98.21MB</li>
						<li class="comment">感受疯狂刺激的夜间飚车</li>
					</ul>
					<ul class="col2">
						<li class="icon"><img src="http://r.anfone.com/upload/icon/ICON_1339123324423.png" width="52" height="51"></li>
						<li class="name"><a href="/soft/35645.html">饥饿的小猫</a></li>
						<li class="info"><i class="df-star star-3"></i> 3.99MB</li>
						<li class="comment">一款小猫风格超可爱的连连看游戏</li>
					</ul>
					<ul class="col2">
						<li class="icon"><img src="http://r.anfone.com/upload/icon/ICON_1335250957616.png" width="52" height="51"></li>
						<li class="name"><a href="/soft/30507.html">鳄鱼爱洗澡（无敌版）</a></li>
						<li class="info"><i class="df-star star-4"></i> 37.28MB</li>
						<li class="comment">迪斯尼出品精美的益智休闲游戏</li>
					</ul>
					<ul class="col2">
						<li class="icon"><img src="http://r.anfone.com/upload/icon/ICON_1339034760753.png" width="52" height="51"></li>
						<li class="name"><a href="/soft/35466.html">小熊推金币</a></li>
						<li class="info"><i class="df-star star-3"></i> 19.61MB</li>
						<li class="comment">最受欢迎的推金币游戏</li>
					</ul>
					<ul class="col2">
						<li class="icon"><img src="http://r.anfone.com/upload/icon/ICON_1337758998962.png" width="52" height="51"></li>
						<li class="name"><a href="/soft/33808.html">一点碎屏</a></li>
						<li class="info"><i class="df-star star-5"></i> 443.10KB</li>
						<li class="comment">手机屏幕碎了可蛋疼了</li>
					</ul>
					<ul class="col2">
						<li class="icon"><img src="http://r.anfone.com/upload/icon/ICON_1333000060799.png" width="52" height="51"></li>
						<li class="name"><a href="/soft/26366.html">忍者无极</a></li>
						<li class="info"><i class="df-star star-4"></i> 32.02MB</li>
						<li class="comment">日本人气第一忍术动作游戏</li>
					</ul>
					<ul class="col2">
						<li class="icon"><img src="http://r.anfone.com/upload/icon/ICON_1329208248539.png" width="52" height="51"></li>
						<li class="name"><a href="/soft/25318.html">3D弓箭手</a></li>
						<li class="info"><i class="df-star star-3"></i> 26.08MB</li>
						<li class="comment">另类独特的超酷射箭游戏</li>
					</ul>
					<ul class="col2">
						<li class="icon"><img src="http://r.anfone.com/upload/icon/ICON_1332312836327.png" width="52" height="51"></li>
						<li class="name"><a href="/soft/27361.html">声速赛车</a></li>
						<li class="info"><i class="df-star star-4"></i> 16.31MB</li>
						<li class="comment">用嗓门来疯狂赛车</li>
					</ul>
					<ul class="col2">
						<li class="icon"><img src="http://r.anfone.com/upload/icon/ICON_1336631006398.png" width="52" height="51"></li>
						<li class="name"><a href="/soft/32227.html">动物管理员</a></li>
						<li class="info"><i class="df-star star-3"></i> 4.56MB</li>
						<li class="comment">画面非常独特的消除类的游戏</li>
					</ul>
					<ul class="col2">
						<li class="icon"><img src="http://r.anfone.com/upload/icon/ICON_1337919141885.png" width="52" height="51"></li>
						<li class="name"><a href="/soft/34078.html">太平洋空战</a></li>
						<li class="info"><i class="df-star star-5"></i> 11.74MB</li>
						<li class="comment">一款3D空战射击类游戏</li>
					</ul>
				</div>
			</div>
		</div>
	</div>

	<div class="column-r-box">
		<div class="column-r row-430">
			<ul class="title-r">
				<li>热门游戏排行榜</li>
			</ul>
			<ul class="sort-r" id="game-tab_0">
			  <li><em class="top">01</em><a href="/soft/8258.html">会说话的汤姆猫完整版</a></li>
			  <li><em class="top">02</em><a href="/soft/26478.html">植物大战僵尸（微云版）</a></li>
			  <li><em class="top">03</em><a href="/soft/21090.html">企鹅跳</a></li>
			  <li><em>04</em><a href="/soft/30507.html">鳄鱼爱洗澡（无敌版）</a></li>
			  <li><em>05</em><a href="/soft/25724.html">愤怒的小鸟两周年纪念版</a></li>
			  <li><em>06</em><a href="/soft/31116.html">水果忍者(中国版)</a></li>
			  <li><em>07</em><a href="/soft/29228.html">熊猫屁王</a></li>
			  <li><em>08</em><a href="/soft/34324.html">捕鱼达人官方版</a></li>
			  <li><em>09</em><a href="/soft/30258.html">吹裙子</a></li>
			  <li><em>10</em><a href="/soft/23273.html">不朽的神迹中文破解版</a></li>
			</ul>
		</div>
		<div class="clear"></div>
	</div>
</div>

