<div class="sect m-t15">
    <div class="sect-main">
        <div class="arti">
            <div class="arti-hd arti-hd-bar">
                <div class="arti-hd-c">
                    <div class="arti-hd-c-content">
                        <h3 class="arti-hd-title">
                            <span class="ico-android">装机必备</span></h3>
                        <span class="arti-hd-more"><a class="a-s4" href="http://m.163.com/android/game_recommend.html">
                            更多&gt;&gt;</a></span>
                    </div>
                </div>
                <span class="arti-hd-l"></span><span class="arti-hd-r"></span>
            </div>
            <div class="arti-bd">
                <div class="arti-bd-content">
                    <ul class="p-v20 t-c clearfix">
                        <? for($i = 0; $i < 6; $i++){ ?>
                            <li class="li-hori-w122">
                                <div class="box-app">
                                    <p>
                                        <a href="http://m.163.com/android/software/31e75h.html" class="img-app"><i class="img-app-none">
                                        </i>
                                            <img src="http://img6.ph.126.net/YRM1keZGTYOZjZ-NRrIvQg==/1354457587949293196.png"
                                                width="70" height="70">
                                        </a>
                                    </p>
                                    <h5 class="t-overflow m-t8">
                                        <a href="http://m.163.com/android/software/31e75h.html">高速骑士</a></h5>
                                    <p class="app-price-line">
                                        <span class="price-new"><i></i>竞速游戏</span>
                                    </p>
                                    <p class="app-download-line" style="display: none;">
                                        <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&id=2177969&pf=2&cg=CA96B6ICJ11&sign=cbed28e08664b10a929da33cfeda2f62&url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201206%2F11%2Fcom.batteryacid.highwayrider-1.apk"
                                            class="button-cmn button-s1">免费下载 </a>
                                    </p>
                                    <div class="box-app-detail">
                                        <h2 class="f-s2">
                                            高速骑士</h2>
                                        <h2 class="price-new c-orange f-bold">
                                            免费</h2>
                                        <p class="m-t5 c-gray">
                                            含有众多恶搞成分的竞速游戏。
                                        </p>
                                        <p class="m-t5">
                                            <span class="fl-r c-gray">27804人推荐</span>
                                        </p>
                                        <p>
                                            <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 0%">
                                            </i></span><span class="vote-text c-gray">0.0</span>
                                        </p>
                                    </div>
                                </div>
                            </li>
                        <?}?>
                    </ul>
                    <ul class="p-b15 t-c clearfix">
                        <? for($i = 0; $i < 6; $i++){ ?>
                            <li class="li-hori-w122">
                                <div class="box-app">
                                    <p>
                                        <a href="http://m.163.com/android/software/31akh5.html" class="img-app"><i class="img-app-none">
                                        </i>
                                            <img src="http://img6.ph.126.net/YRM1keZGTYOZjZ-NRrIvQg==/1354457587949293196.png"
                                                width="70" height="70">
                                        </a>
                                    </p>
                                    <h5 class="t-overflow m-t8">
                                        <a href="http://m.163.com/android/software/31akh5.html">加菲食物保卫战</a></h5>
                                    <p class="app-price-line">
                                        <span class="price-new"><i></i>休闲益智</span>
                                    </p>
                                    <p class="app-download-line" style="display: none;">
                                        <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&id=2060581&pf=2&cg=CA96B6HQND1&sign=c7f69d2d42edfcd7d66786cc042f3e90&url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201206%2F11%2Fcom.webprancer.google.garfieldDefense-2.apk"
                                            class="button-cmn button-s1">免费下载 </a>
                                    </p>
                                    <div class="box-app-detail">
                                        <h2 class="f-s2">
                                            加菲食物保卫战</h2>
                                        <h2 class="price-new c-orange f-bold">
                                            免费</h2>
                                        <p class="m-t5 c-gray">
                                            加菲猫主题塔防游戏，游戏性颇佳。
                                        </p>
                                        <p class="m-t5">
                                            <span class="fl-r c-gray">46177人推荐</span>
                                        </p>
                                        <p>
                                            <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 86%">
                                            </i></span><span class="vote-text c-gray">8.6</span>
                                        </p>
                                    </div>
                                </div>
                            </li>
                        <?}?>
                    </ul>
                </div>
            </div>
            <div class="arti-ft">
                <div class="arti-ft-c">
                    <div class="arti-ft-c-content">
                    </div>
                </div>
                <span class="arti-ft-l"></span><span class="arti-ft-r"></span>
            </div>
        </div>
        <div class="arti m-t15">
        </div>
        <div class="arti">
            <div class="arti-hd arti-hd-bar">
                <div class="arti-hd-c">
                    <div class="arti-hd-c-content">
                        <h3 class="arti-hd-title">
                            <span class="ico-android">游戏推荐</span></h3>
                        <span class="arti-hd-more"><a class="a-s4" href="http://m.163.com/android/app_recommend.html">
                            更多&gt;&gt;</a></span>
                    </div>
                </div>
                <span class="arti-hd-l"></span><span class="arti-hd-r"></span>
            </div>
            <div class="arti-bd">
                <div class="arti-bd-content">
                    <ul class="p-v20 t-c clearfix">
                        <? for($i = 0; $i < 6; $i++){ ?>
                            <li class="li-hori-w122">
                                <div class="box-app">
                                    <p>
                                        <a href="http://m.163.com/android/software/2vtv2e.html" class="img-app"><i class="img-app-none">
                                        </i>
                                            <img src="http://img6.ph.126.net/YRM1keZGTYOZjZ-NRrIvQg==/1354457587949293196.png"
                                                width="70" height="70">
                                        </a>
                                    </p>
                                    <h5 class="t-overflow m-t8">
                                        <a href="http://m.163.com/android/software/2vtv2e.html">在线搜图</a></h5>
                                    <p class="app-price-line">
                                        <span class="price-new"><i></i>影音</span>
                                    </p>
                                    <p class="app-download-line" style="display: none;">
                                        <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&id=596814&pf=2&cg=CA8MTH1D1V1&sign=4de210208e97c709de7cbe7907e61f17&url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201206%2F12%2Forg.droidiris-100.apk"
                                            class="button-cmn button-s1">免费下载 </a>
                                    </p>
                                    <div class="box-app-detail">
                                        <h2 class="f-s2">
                                            在线搜图</h2>
                                        <h2 class="price-new c-orange f-bold">
                                            免费</h2>
                                        <p class="m-t5 c-gray">
                                            一款在线搜索图片的应用，内置各家搜索引擎，搜索的图片以3D网格…
                                        </p>
                                        <p class="m-t5">
                                            <span class="fl-r c-gray">10088人推荐</span>
                                        </p>
                                        <p>
                                            <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 0%">
                                            </i></span><span class="vote-text c-gray">0.0</span>
                                        </p>
                                    </div>
                                </div>
                            </li>
                        <?}?>
                    </ul>
                    <ul class="p-b15 t-c clearfix">
                        <? for($i = 0; $i < 6; $i++){ ?>
                            <li class="li-hori-w122">
                                <div class="box-app">
                                    <p>
                                        <a href="http://m.163.com/android/software/316feo.html" class="img-app"><i class="img-app-none">
                                        </i>
                                            <img src="http://img6.ph.126.net/YRM1keZGTYOZjZ-NRrIvQg==/1354457587949293196.png"
                                                width="70" height="70">
                                        </a>
                                    </p>
                                    <h5 class="t-overflow m-t8">
                                        <a href="http://m.163.com/android/software/316feo.html">传感音乐播放器</a></h5>
                                    <p class="app-price-line">
                                        <span class="price-new"><i></i>影音</span>
                                    </p>
                                    <p class="app-download-line" style="display: none;">
                                        <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&id=1924312&pf=2&cg=CA8MTH1D1V1&sign=0e31a647d9db07b87bf9c3771e79392c&url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201205%2F03%2Fcom.zgui.musicshaker-54.apk"
                                            class="button-cmn button-s1">免费下载 </a>
                                    </p>
                                    <div class="box-app-detail">
                                        <h2 class="f-s2">
                                            传感音乐播放器</h2>
                                        <h2 class="price-new c-orange f-bold">
                                            免费</h2>
                                        <p class="m-t5 c-gray">
                                            依靠四种体感模式就可快速换歌的音乐播放器。
                                        </p>
                                        <p class="m-t5">
                                            <span class="fl-r c-gray">86371人推荐</span>
                                        </p>
                                        <p>
                                            <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 73%">
                                            </i></span><span class="vote-text c-gray">7.3</span>
                                        </p>
                                    </div>
                                </div>
                            </li>
                        <?}?>
                    </ul>
                </div>
            </div>
            <div class="arti-ft">
                <div class="arti-ft-c">
                    <div class="arti-ft-c-content">
                    </div>
                </div>
                <span class="arti-ft-l"></span><span class="arti-ft-r"></span>
            </div>
        </div>
    </div>
    <div class="sect-side">
        <div class="arti side-show-detail" id="yui_3_4_0_4_1339546066975_1096">
            <div class="arti-hd arti-hd-bar">
                <div class="arti-hd-c">
                    <div class="arti-hd-c-content">
                        <h3 class="arti-hd-title">
                            <span class="ico-android">热门游戏排行榜</span></h3>
                    </div>
                </div>
                <span class="arti-hd-l"></span><span class="arti-hd-r"></span>
            </div>
            <div class="arti-bd" id="yui_3_4_0_4_1339546066975_1104">
                <div class="arti-bd-content" id="yui_3_4_0_4_1339546066975_1103">
                    <div class="m-h10" id="yui_3_4_0_4_1339546066975_1102">
                        <ol id="yui_3_4_0_4_1339546066975_1101">
                            <li class="li-rank li-rank-first" id="yui_3_4_0_4_1339546066975_1100">
                                <div class="li-rank-hd">
                                    <span class="li-rank-num"><i class="logo-num1"></i></span>
                                    <h5 class="li-rank-title-s t-overflow">
                                        <a href="http://m.163.com/android/software/2vbrqf.html">会说话的汤姆猫</a></h5>
                                </div>
                                <div class="li-rank-bd li-rank-unfold" id="yui_3_4_0_4_1339546066975_1099" style="">
                                    <div class="li-rank-text" id="yui_3_4_0_4_1339546066975_1098">
                                        <div class="li-rank-text-content" id="yui_3_4_0_4_1339546066975_1097">
                                            <p class="app-download-line p-t5">
                                                <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&id=3663&pf=2&cg=CA96B6HQND1&sign=e9bbc269fdc7802b12f208793aea6ed5&url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201111%2F13%2Fcom.outfit7.talkingtom_34.apk"
                                                    class="btn-cmn btn-s1">免费下载</a></p>
                                            <p class="m-t5 c-gray" id="yui_3_4_0_4_1339546066975_1095">
                                                休闲益智</p>
                                            <p>
                                                <span class="vote-column"><i style="width: 87%"></i></span><span class="vote-text c-gray">
                                                    8.7</span></p>
                                        </div>
                                    </div>
                                    <div class="li-rank-img">
                                        <a href="http://m.163.com/android/software/2vbrqf.html" class="img-app"><i class="img-app-none">
                                        </i>
                                            <img src="/upload/icon/28991922618645254.png"
                                                width="70" height="70"></a>
                                    </div>
                                </div>
                            </li>
                            <? for($i = 2; $i <= 13; $i++){ ?>
                                <li class="li-rank">
                                    <div class="li-rank-hd">
                                        <span class="li-rank-num"><i class="logo-num<?=$i?>"></i></span>
                                        <h5 class="li-rank-title-s t-overflow">
                                            <a href="http://m.163.com/android/software/2vdd03.html">会说话的狗狗</a></h5>
                                    </div>
                                    <div class="li-rank-bd" style="display: none;">
                                        <div class="li-rank-text">
                                            <div class="li-rank-text-content">
                                                <p class="app-download-line p-t5">
                                                    <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&id=54019&pf=2&cg=CA96B6HQND1&sign=9482ed3cc2feefbf80cdfa80a2cf1e82&url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201203%2F16%2Fcom.outfit7.talkingben-8.apk"
                                                        class="btn-cmn btn-s1">免费下载</a></p>
                                                <p class="m-t5 c-gray">
                                                    休闲益智</p>
                                                <p>
                                                    <span class="vote-column"><i style="width: 81%"></i></span><span class="vote-text c-gray">
                                                        8.1</span></p>
                                            </div>
                                        </div>
                                        <div class="li-rank-img">
                                            <a href="http://m.163.com/android/software/2vdd03.html" class="img-app"><i class="img-app-none">
                                            </i>
                                                <img src="/upload/icon/28991922618645254.png"
                                                    width="70" height="70"></a>
                                        </div>
                                    </div>
                                </li>
                            <?}?>
                        </ol>
                    </div>
                </div>
            </div>
            <div class="arti-ft">
                <div class="arti-ft-c">
                    <div class="arti-ft-c-content">
                    </div>
                </div>
                <span class="arti-ft-l"></span><span class="arti-ft-r"></span>
            </div>
        </div>
    </div>
</div>


















































<div class="sect m-t15">
    <div class="sect-main">
        <div class="arti">
            <div class="arti-hd arti-hd-bar">
                <div class="arti-hd-c">
                    <div class="arti-hd-c-content">
                        <h3 class="arti-hd-title">
                            <span class="ico-android">新品推荐</span></h3>
                        <span class="arti-hd-more"><a class="a-s4" href="/android/new_recommend.html">更多&gt;&gt;</a></span>
                    </div>
                </div>
                <span class="arti-hd-l"></span><span class="arti-hd-r"></span>
            </div>
            <div class="arti-bd">
                <div class="arti-bd-content">
                    <ul class="p-v20 t-c clearfix">
                        <? for($i = 0; $i < 6; $i++){ ?>
                            <li class="li-hori-w122">
                                <div class="box-app" id="yui_3_4_0_4_1339548940557_11709">
                                    <p>
                                        <a href="/android/software/31di3f.html" class="img-app"><i class="img-app-none"></i>
                                            <img src="http://img8.ph.126.net/Jyox1mFK7FLo3P7WrmyZ0g==/613333974270136518.png"
                                                width="70" height="70">
                                        </a>
                                    </p>
                                    <h5 class="t-overflow m-t8">
                                        <a href="/android/software/31di3f.html">欢乐欧洲杯</a></h5>
                                    <p class="app-price-line" style="">
                                        <span class="price-new"><i></i>体育游戏</span>
                                    </p>
                                    <p class="app-download-line" style="display: none;">
                                        <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&amp;id=2156399&amp;pf=2&amp;cg=CA96B6I1VH1&amp;sign=d47aa26399b6c2f3825b46cb8a161110&amp;url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201206%2F11%2Fourcup.apk"
                                            class="button-cmn button-s1">免费下载 </a>
                                    </p>
                                    <div class="box-app-detail">
                                        <h2 class="f-s2">
                                            欢乐欧洲杯</h2>
                                        <h2 class="price-new c-orange f-bold">
                                            免费</h2>
                                        <p class="m-t5 c-gray">
                                            安卓平台最好玩的欧洲杯主题社交竞猜游戏 欢乐欧洲杯是android …
                                        </p>
                                        <p class="m-t5">
                                            <span class="fl-r c-gray">2747人推荐</span>
                                        </p>
                                        <p>
                                            <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 100%">
                                            </i></span><span class="vote-text c-gray">10.0</span>
                                        </p>
                                    </div>
                                </div>
                            </li>
                        <?}?>
                    </ul>
                    <ul class="p-b15 t-c clearfix">
                        <? for($i = 0; $i < 6; $i++){ ?>
                            <li class="li-hori-w122">
                                <div class="box-app" id="yui_3_4_0_4_1339548940557_1730">
                                    <p>
                                        <a href="/android/software/314t4i.html" class="img-app"><i class="img-app-none"></i>
                                            <img src="http://img0.ph.126.net/0sKqCUXIg75-_-A0FL3biQ==/2504282867811887400.png"
                                                width="70" height="70">
                                        </a>
                                    </p>
                                    <h5 class="t-overflow m-t8">
                                        <a href="/android/software/314t4i.html">七星滚球</a></h5>
                                    <p class="app-price-line" style="">
                                        <span class="price-new"><i></i>体育游戏</span>
                                    </p>
                                    <p class="app-download-line" style="display: none;">
                                        <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&amp;id=1872786&amp;pf=2&amp;cg=CA96B6I1VH1&amp;sign=787a48fa1c99ed7e293eb2e17a0664a0&amp;url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201203%2F27%2Fcom.IdealBall-25.apk"
                                            class="button-cmn button-s1">免费下载 </a>
                                    </p>
                                    <div class="box-app-detail">
                                        <h2 class="f-s2">
                                            七星滚球</h2>
                                        <h2 class="price-new c-orange f-bold">
                                            免费</h2>
                                        <p class="m-t5 c-gray">
                                            画面和配乐都充满中国风的滚珠游戏。
                                        </p>
                                        <p class="m-t5">
                                            <span class="fl-r c-gray">215500人推荐</span>
                                        </p>
                                        <p>
                                            <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 73%">
                                            </i></span><span class="vote-text c-gray">7.3</span>
                                        </p>
                                    </div>
                                </div>
                            </li>
                        <?}?>
                    </ul>
                </div>
            </div>
            <div class="arti-ft">
                <div class="arti-ft-c">
                    <div class="arti-ft-c-content">
                    </div>
                </div>
                <span class="arti-ft-l"></span><span class="arti-ft-r"></span>
            </div>
        </div>
        <div class="arti m-t15"></div>
        <div class="arti">
            <div class="arti-hd arti-hd-bar">
                <div class="arti-hd-c">
                    <div class="arti-hd-c-content">
                        <h3 class="arti-hd-title">
                            <span class="ico-android">热门分类</span></h3>
                    </div>
                </div>
                <span class="arti-hd-l"></span><span class="arti-hd-r"></span>
            </div>
            <div class="arti-bd">
                <div class="arti-bd-content">
                    <div class="p-t30 p-b20 arti-bg-w240">
                        <ul class="clearfix">
                            <? $topics = array("省钱利器","美容护肤", "时尚阅读"); ?>
                            <? foreach ($topics as $topic) { ?>
                                <li class="li-hori-w240">
                                    <div class="m-h15">
                                        <p class="t-c">
                                            <a href="http://m.163.com/android/category/ca8mth20dq/index.html" class="btn-cat"
                                                target="_self"><?= $topic ?></a></p>
                                        <ol class="m-t25 list-category-top">
                                            <?php for($i=0;$i<6;$i++) {?>
                                                <li class="li-rank-first" id="yui_3_4_0_4_1339547997667_1027">
                                                    <div class="li-rank-hd">
                                                        <span class="li-rank-thumb"><a href="http://m.163.com/android/software/30rvnt.html"
                                                            class="img-app-s"><i class="img-app-s-none"></i>
                                                            <img src="http://img8.ph.126.net/hhQpgsn2q8jtyrO8ltQYeQ==/2793639143870788368.png"
                                                                width="30" height="30"></a></span>
                                                        <h5 class="li-rank-title t-overflow">
                                                            <a href="http://m.163.com/android/software/30rvnt.html">糗事百科</a></h5>
                                                        <span class="li-rank-desc-s" style=""><span class="c-gray">&gt;100W人推荐</span></span>
                                                        <div class="li-rank-download" style="display: none;">
                                                            <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&amp;id=1580541&amp;pf=2&amp;cg=CA8MTH20DQ1&amp;sign=877e5df6c6f6717a6a0daffe03fef988&amp;url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201205%2F22%2Fqiushibaike.apk"
                                                                class="button-cmn button-s1">免费下载 </a>
                                                        </div>
                                                    </div>
                                                </li>
                                            <?}?>
                                        </ol>
                                    </div>
                                </li>
                            <?}?>
                        </ul>
                    </div>
                    <div class="p-t30 p-b20 arti-bg-w240">
                        <ul class="clearfix">
                            <? $topics = array("美食旅游","摄影电影", "手机防毒"); ?>
                            <? foreach ($topics as $topic) { ?>
                                <li class="li-hori-w240">
                                    <div class="m-h15">
                                        <p class="t-c">
                                            <a href="http://m.163.com/android/category/ca8mth20dq/index.html" class="btn-cat"
                                                target="_self"><?= $topic ?></a></p>
                                        <ol class="m-t25 list-category-top">
                                            <?php for($i=0;$i<6;$i++) {?>
                                                <li class="li-rank-first" id="yui_3_4_0_4_1339547997667_1027">
                                                    <div class="li-rank-hd">
                                                        <span class="li-rank-thumb"><a href="http://m.163.com/android/software/30rvnt.html"
                                                            class="img-app-s"><i class="img-app-s-none"></i>
                                                            <img src="http://img8.ph.126.net/hhQpgsn2q8jtyrO8ltQYeQ==/2793639143870788368.png"
                                                                width="30" height="30"></a></span>
                                                        <h5 class="li-rank-title t-overflow">
                                                            <a href="http://m.163.com/android/software/30rvnt.html">糗事百科</a></h5>
                                                        <span class="li-rank-desc-s" style=""><span class="c-gray">&gt;100W人推荐</span></span>
                                                        <div class="li-rank-download" style="display: none;">
                                                            <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&amp;id=1580541&amp;pf=2&amp;cg=CA8MTH20DQ1&amp;sign=877e5df6c6f6717a6a0daffe03fef988&amp;url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201205%2F22%2Fqiushibaike.apk"
                                                                class="button-cmn button-s1">免费下载 </a>
                                                        </div>
                                                    </div>
                                                </li>
                                            <?}?>
                                        </ol>
                                    </div>
                                </li>
                            <?}?>
                        </ul>
                    </div>
                    <div>
                        <div class="p-v20 t-c">
                            <a href="javascript:void(0);" class="button-cmn button-s3" id="A1" target="_self"><span
                                class="icon-arrow">查看全部分类</span></a></div>
                    </div>
                </div>
            </div>
            <div class="arti-ft">
                <div class="arti-ft-c">
                    <div class="arti-ft-c-content">
                    </div>
                </div>
                <span class="arti-ft-l"></span><span class="arti-ft-r"></span>
            </div>
        </div>
    </div>
    <div class="sect-side">
        <div class="arti side-show-detail">
            <div class="arti-hd arti-hd-bar">
                <div class="arti-hd-c">
                    <div class="arti-hd-c-content">
                        <h3 class="arti-hd-title">
                            <span class="ico-android">热门应用排行榜</span></h3>
                    </div>
                </div>
                <span class="arti-hd-l"></span><span class="arti-hd-r"></span>
            </div>
            <div class="arti-bd">
                <div class="arti-bd-content">
                    <div class="m-h10">
                        <ol>
                            <li class="li-rank li-rank-first">
                                <div class="li-rank-hd">
                                    <span class="li-rank-num"><i class="logo-num1"></i></span>
                                    <h5 class="li-rank-title-s t-overflow">
                                        <a href="http://m.163.com/android/software/2vbuca.html">高德导航公众版</a></h5>
                                </div>
                                <div class="li-rank-bd li-rank-unfold">
                                    <div class="li-rank-text">
                                        <div class="li-rank-text-content">
                                            <p class="app-download-line p-t5">
                                                <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&id=6282&pf=2&cg=CA8MTH056G1&sign=2a9ebad2c0248746677020ee9c8c982a&url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201112%2F07%2FAutonavi_v1.2.apk"
                                                    class="btn-cmn btn-s1">免费下载</a></p>
                                            <p class="m-t5 c-gray">
                                                导航</p>
                                            <p>
                                                <span class="vote-column"><i style="width: 68%"></i></span><span class="vote-text c-gray">
                                                    6.8</span></p>
                                        </div>
                                    </div>
                                    <div class="li-rank-img">
                                        <a href="http://m.163.com/android/software/2vbuca.html" class="img-app"><i class="img-app-none">
                                        </i>
                                            <img src="http://img6.ph.126.net/YRM1keZGTYOZjZ-NRrIvQg==/1354457587949293196.png"
                                                width="70" height="70"></a>
                                    </div>
                                </div>
                            </li>
                            <? for($i=2;$i<=13;$i++){?>
                                <li class="li-rank">
                                    <div class="li-rank-hd">
                                        <span class="li-rank-num"><i class="logo-num<?=$i?>"></i></span>
                                        <h5 class="li-rank-title-s t-overflow">
                                            <a href="http://m.163.com/android/software/2vbrks.html">网易新闻</a></h5>
                                    </div>
                                    <div class="li-rank-bd" style="display: none;">
                                        <div class="li-rank-text">
                                            <div class="li-rank-text-content">
                                                <p class="app-download-line p-t5">
                                                    <a href="#" class="btn-cmn btn-s1">免费下载</a></p>
                                                <p class="m-t5 c-gray">
                                                    新闻</p>
                                                <p>
                                                    <span class="vote-column"><i style="width: 90%"></i></span><span class="vote-text c-gray">
                                                        9.0</span></p>
                                            </div>
                                        </div>
                                        <div class="li-rank-img">
                                            <a href="http://m.163.com/android/software/2vbrks.html" class="img-app"><i class="img-app-none">
                                            </i>
                                                <img src="http://img6.ph.126.net/YRM1keZGTYOZjZ-NRrIvQg==/1354457587949293196.png"
                                                    width="70" height="70"></a>
                                        </div>
                                    </div>
                                </li>
                            <?}?>
                        </ol>
                    </div>
                </div>
            </div>
            <div class="arti-ft">
                <div class="arti-ft-c">
                    <div class="arti-ft-c-content">
                    </div>
                </div>
                <span class="arti-ft-l"></span><span class="arti-ft-r"></span>
            </div>
        </div>
    </div>
</div>