<div class="sect">
	<div class="crumb">当前位置： <a target="_self" href="/android.html">Android首页</a>
    &gt; <a target="_self" href="/android/game.html">Android游戏</a>
	</div>
</div>

<div class="sect">
	<div class="arti">
		<div class="arti-hd arti-hd-bar">
			<div class="arti-hd-c">
				<div class="arti-hd-c-content">
					<h3 class="arti-hd-title">
						<span id="ico-android">
							<span>全部游戏</span>	
						</span>
					</h3>
				</div>
        	</div>
			<span class="arti-hd-l"></span>
			<span class="arti-hd-r"></span>
        </div>
		<div class="arti-bd">
			<div class="arti-bd-content">				
				<div class="yui3-appsview-content" id="appsview">
					<div class="yui3-appsview-list">
						<ul class="list-appsview clearfix">
							<?for($i = 0; $i < 10; $i++){?>
								<li>
				                    <div class="m-h15 p-v25">
				                        <div class="apps-info">
				                            <div class="apps-info-text">
				                                <div class="apps-info-text-content">
				                                    <p class="f-s3 t-overflow"><a href="/android/software/2vbrqf.html">会说话的汤姆猫(Talking Tom Cat Free)</a></p>
				                                    <p class="m-t5"><span class="c-gray">&gt;100W人推荐</span></p>
				                                    <p class="m-t5">
				                                        <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&amp;id=3663&amp;pf=2&amp;cg=CA96B6HQND1&amp;sign=e9bbc269fdc7802b12f208793aea6ed5&amp;url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201111%2F13%2Fcom.outfit7.talkingtom_34.apk" class="fl-r button-cmn button-s1">免费下载</a>
				                                        <span class="vote-column"><i style="width:87%"></i></span><span class="vote-text">87</span>
				                                    </p>
				                                </div>
				                            </div>
				                            <div class="apps-info-img">
				                                <a href="/android/software/2vbrqf.html" class="img-app">
				                                    <i class="img-app-none"></i>
													<i class="img-app-"></i>
				                                    <img src="http://img4.ph.126.net/PnnX8lk87Al1bAHiaIzypg==/28991922618645254.png" width="70" height="70">
				                                </a>
				                            </div>
				                        </div>
				                    </div>
				                </li>
				            <?}?>
						</ul>
					</div>
				</div>
				<div class="yui3-appsview-page">
 					<a href="#prev" target="_self" class="yui3-appsview-page-ctrl yui3-appsview-page-disabled">上一页</a>
 					<a title="第1页" class="yui3-appsview-page-num yui3-appsview-page-current">1	</a>
 					<a title="第2页" href="/android/game/allgame/all-download-2.html" target="_self" class="yui3-appsview-page-num">2</a>
 					<a title="第3页" href="/android/game/allgame/all-download-3.html" target="_self" class="yui3-appsview-page-num">3</a>
 					<a title="第4页" href="/android/game/allgame/all-download-4.html" target="_self" class="yui3-appsview-page-num">4</a>
 					<a title="第5页" href="/android/game/allgame/all-download-5.html" target="_self" class="yui3-appsview-page-num">5</a>
 					<a title="第6页" href="/android/game/allgame/all-download-6.html" target="_self" class="yui3-appsview-page-num">6</a>
					<span class="yui3-appsview-page-ellipsis">……</span>
					<a title="第273页" href="/android/game/allgame/all-download-273.html" target="_self" class="yui3-appsview-page-num">273</a>
					<a title="第2页" href="/android/game/allgame/all-download-2.html" target="_self" class="yui3-appsview-page-ctrl">下一页</a>
				</div>
        	</div>
        </div>
		<div class="arti-ft">
			<div class="arti-ft-c">
				<div class="arti-ft-c-content"></div>
			</div>
			<span class="arti-ft-l"></span>
			<span class="arti-ft-r"></span>
		</div>
	</div>
</div>