<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>aaaaaaaaaaaaaaaaaaaaaaaaaaaa</title>
	<link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/css/main.css">
	<script type="text/javascript" src="/js/jquery1.7.2.min.js"></script>
	<script src="http://www.google-analytics.com/ga.js" type="text/javascript"></script>
</head>
<body>
	<?php echo $this->layout()->content; ?>
</body>
</html>
