<div class="arti">
    <div class="arti-hd arti-hd-bar">
        <div class="arti-hd-c">
            <div class="arti-hd-c-content">
                <h3 class="arti-hd-title">
                    <span class="ico-android">游戏推荐</span></h3>
                <span class="arti-hd-more"><a class="a-s4" href="http://m.163.com/android/app_recommend.html">
                    更多&gt;&gt;</a></span>
            </div>
        </div>
        <span class="arti-hd-l"></span><span class="arti-hd-r"></span>
    </div>
    <div class="arti-bd">
        <div class="arti-bd-content">
            <ul class="p-v20 t-c clearfix">
                <li class="li-hori-w122">
                    <div class="box-app">
                        <p>
                            <a href="/android/app/20.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/20120627100818939.jpg" width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/20.html">照妖镜</a></h5>
                        <p class="app-price-line">
                            <span class="price-new"><i></i>影音娱乐</span>
                        </p>
                        <p class="app-download-line" style="display: none;">
                            <a href="/download/20" class="button-cmn button-s1">免费下载</a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">照妖镜</h2>
                            <h2 class="price-new c-orange f-bold">免费</h2>
                            <p class="m-t5 c-gray">史上最好玩的手机恶搞软件</p>
                            <p class="m-t5"><span class="fl-r c-gray">35029人推荐</span></p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 90%">
                                </i></span>
                            </p>
                        </div>
                    </div>
                </li>
                <li class="li-hori-w122">
                    <div class="box-app">
                        <p>
                            <a href="/android/app/21.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/2012062710201774.png" width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/21.html">爆裂星球</a></h5>
                        <p class="app-price-line" style="">
                            <span class="price-new"><i></i>射击飞行</span>
                        </p>
                        <p class="app-download-line" style="display: none; ">
                            <a href="/download/21" class="button-cmn button-s1">免费下载</a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">爆裂星球</h2>
                            <h2 class="price-new c-orange f-bold">免费</h2>
                            <p class="m-t5 c-gray">保卫地球，对抗邪恶外星侵略者</p>
                            <p class="m-t5"><span class="fl-r c-gray">10927人推荐</span></p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 89%">
                                </i></span>
                            </p>
                        </div>
                    </div>
                </li>
                <li class="li-hori-w122">
                    <div class="box-app">
                        <p>
                            <a href="/android/app/22.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/20120627104023954.png" width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/22.html">忍者变色龙</a></h5>
                        <p class="app-price-line" style="">
                            <span class="price-new"><i></i>益智休闲</span>
                        </p>
                        <p class="app-download-line" style="display: none; ">
                            <a href="/download/22" class="button-cmn button-s1">免费下载</a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">忍者变色龙</h2>
                            <h2 class="price-new c-orange f-bold">免费</h2>
                            <p class="m-t5 c-gray">Gobber是一个可以执行最不可思议的飞行特技的变色龙</p>
                            <p class="m-t5"><span class="fl-r c-gray">10987人推荐</span></p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 85%">
                                </i></span>
                            </p>
                        </div>
                    </div>
                </li>
                <li class="li-hori-w122">
                    <div class="box-app" id="yui_3_4_0_3_1340815876581_162">
                        <p>
                            <a href="/android/app/23.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/20120627110503539.png" width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/23.html">连续益智闯关</a></h5>
                        <p class="app-price-line" style="display: none; ">
                            <span class="price-new"><i></i>益智休闲</span>
                        </p>
                        <p class="app-download-line" style="">
                            <a href="/download/23" class="button-cmn button-s1">免费下载</a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">连续益智闯关</h2>
                            <h2 class="price-new c-orange f-bold">免费</h2>
                            <p class="m-t5 c-gray">一款连续性益智游戏的续集</p>
                            <p class="m-t5"><span class="fl-r c-gray">14356人推荐</span></p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 85%">
                                </i></span>
                            </p>
                        </div>
                    </div>
                </li>
                <li class="li-hori-w122">
                    <div class="box-app">
                        <p>
                            <a href="/android/app/24.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/20120627111240113.png" width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/24.html">忘仙</a></h5>
                        <p class="app-price-line">
                            <span class="price-new"><i></i>角色扮演</span>
                        </p>
                        <p class="app-download-line" style="display: none;">
                            <a href="/download/24" class="button-cmn button-s1">免费下载</a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">忘仙</h2>
                            <h2 class="price-new c-orange f-bold">免费</h2>
                            <p class="m-t5 c-gray">大型3D手游，仙魔决战2012，重建仙境国度！</p>
                            <p class="m-t5"><span class="fl-r c-gray">34239人推荐</span></p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 80%">
                                </i></span>
                            </p>
                        </div>
                    </div>
                </li>
                <li class="li-hori-w122">
                    <div class="box-app">
                        <p>
                            <a href="/android/app/25.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/20120627112600750.png" width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/25.html">抽积木</a></h5>
                        <p class="app-price-line">
                            <span class="price-new"><i></i>益智休闲</span>
                        </p>
                        <p class="app-download-line" style="display: none;">
                            <a href="/download/25" class="button-cmn button-s1">免费下载</a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">抽积木</h2>
                            <h2 class="price-new c-orange f-bold">免费</h2>
                            <p class="m-t5 c-gray">一款从iOS平台上移植过来的相当有趣的搭积木的小游戏</p>
                            <p class="m-t5"><span class="fl-r c-gray">18725人推荐</span></p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 90%">
                                </i></span>
                            </p>
                        </div>
                    </div>
                </li>
            </ul>
            <ul class="p-b15 t-c clearfix">
                <li class="li-hori-w122">
                    <div class="box-app">
                        <p>
                            <a href="/android/app/26.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/20120627114150458.png" width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/26.html">雪球大反击</a></h5>
                        <p class="app-price-line" style="">
                            <span class="price-new"><i></i>益智休闲</span>
                        </p>
                        <p class="app-download-line" style="display: none; ">
                            <a href="/download/26" class="button-cmn button-s1">免费下载</a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">雪球大反击</h2>
                            <h2 class="price-new c-orange f-bold">免费</h2>
                            <p class="m-t5 c-gray">一款雪人报复人类的益智休闲重力感应安卓手机游戏</p>
                            <p class="m-t5"><span class="fl-r c-gray">14563人推荐</span></p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 90%">
                                </i></span>
                            </p>
                        </div>
                    </div>
                </li>
                <li class="li-hori-w122">
                    <div class="box-app">
                        <p>
                            <a href="/android/app/27.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/20120627115446515.jpg" width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/27.html">捕鱼达人</a></h5>
                        <p class="app-price-line">
                            <span class="price-new"><i></i>益智休闲</span>
                        </p>
                        <p class="app-download-line" style="display: none;">
                            <a href="/download/27" class="button-cmn button-s1">免费下载</a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">捕鱼达人</h2>
                            <h2 class="price-new c-orange f-bold">免费</h2>
                            <p class="m-t5 c-gray">一款超过5千万人在玩的游戏</p>
                            <p class="m-t5"><span class="fl-r c-gray">12856人推荐</span></p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 95%">
                                </i></span>
                            </p>
                        </div>
                    </div>
                </li>
                <li class="li-hori-w122">
                    <div class="box-app">
                        <p>
                            <a href="/android/app/28.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/2012062812021665.jpg" width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/28.html">会说话的汤姆猫</a></h5>
                        <p class="app-price-line">
                            <span class="price-new"><i></i>益智休闲</span>
                        </p>
                        <p class="app-download-line" style="display: none;">
                            <a href="/download/28" class="button-cmn button-s1">免费下载</a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">会说话的汤姆猫</h2>
                            <h2 class="price-new c-orange f-bold">免费</h2>
                            <p class="m-t5 c-gray">汤姆是一只宠物猫,心情不好时跟他聊聊天或抚摸它会让您心情舒畅</p>
                            <p class="m-t5"><span class="fl-r c-gray">21093人推荐</span></p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 95%">
                                </i></span>
                            </p>
                        </div>
                    </div>
                </li>
                <li class="li-hori-w122">
                    <div class="box-app">
                        <p>
                            <a href="/android/app/29.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/20120628120845816.jpg" width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/29.html">水果忍者</a></h5>
                        <p class="app-price-line" style="">
                            <span class="price-new"><i></i>益智休闲</span>
                        </p>
                        <p class="app-download-line" style="display: none; ">
                            <a href="/download/29" class="button-cmn button-s1">免费下载</a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">水果忍者</h2>
                            <h2 class="price-new c-orange f-bold">免费</h2>
                            <p class="m-t5 c-gray">刺激好玩、容易上手却教人难以离手的休闲动作游戏</p>
                            <p class="m-t5"><span class="fl-r c-gray">10294人推荐</span></p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 95%">
                                </i></span>
                            </p>
                        </div>
                    </div>
                </li>
                <li class="li-hori-w122">
                    <div class="box-app">
                        <p>
                            <a href="/android/app/30.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/20120628121604286.png" width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/30.html">咕咕鸡</a></h5>
                        <p class="app-price-line">
                            <span class="price-new"><i></i>射击飞行</span>
                        </p>
                        <p class="app-download-line" style="display: none;">
                            <a href="/download/30" class="button-cmn button-s1">免费下载</a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">咕咕鸡</h2>
                            <h2 class="price-new c-orange f-bold">免费</h2>
                            <p class="m-t5 c-gray">????????</p>
                            <p class="m-t5"><span class="fl-r c-gray">23510人推荐</span></p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 90%">
                                </i></span>
                            </p>
                        </div>
                    </div>
                </li>
                <li class="li-hori-w122">
                    <div class="box-app">
                        <p>
                            <a href="/android/app/31.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/20120628122351889.png" width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/31.html">愤怒的小鸟</a></h5>
                        <p class="app-price-line" style="">
                            <span class="price-new"><i></i>射击飞行</span>
                        </p>
                        <p class="app-download-line" style="display: none; ">
                            <a href="/download/31" class="button-cmn button-s1">免费下载</a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">愤怒的小鸟</h2>
                            <h2 class="price-new c-orange f-bold">免费</h2>
                            <p class="m-t5 c-gray">世界著名休闲游戏之一，开创了怒鸟类型游戏</p>
                            <p class="m-t5"><span class="fl-r c-gray">52041人推荐</span></p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 90%">
                                </i></span>
                            </p>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <div class="arti-ft">
        <div class="arti-ft-c">
            <div class="arti-ft-c-content">
            </div>
        </div>
        <span class="arti-ft-l"></span><span class="arti-ft-r"></span>
    </div>
</div>