<div class="arti">
    <div class="arti-hd arti-hd-bar">
        <div class="arti-hd-c">
            <div class="arti-hd-c-content">
                <h3 class="arti-hd-title">
                    <span class="ico-android">游戏推荐</span></h3>
                <span class="arti-hd-more"><a class="a-s4" href="http://m.163.com/android/app_recommend.html">
                    更多&gt;&gt;</a></span>
            </div>
        </div>
        <span class="arti-hd-l"></span><span class="arti-hd-r"></span>
    </div>
    <div class="arti-bd">
        <div class="arti-bd-content">
            <ul class="p-v20 t-c clearfix">
                <? for($i = 0; $i < 6; $i++){ ?>
                    <li class="li-hori-w122">
                        <div class="box-app">
                            <p>
                                <a href="http://m.163.com/android/software/2vtv2e.html" class="img-app"><i class="img-app-none">
                                </i>
                                    <img src="http://img6.ph.126.net/YRM1keZGTYOZjZ-NRrIvQg==/1354457587949293196.png"
                                        width="70" height="70">
                                </a>
                            </p>
                            <h5 class="t-overflow m-t8">
                                <a href="http://m.163.com/android/software/2vtv2e.html">在线搜图</a></h5>
                            <p class="app-price-line">
                                <span class="price-new"><i></i>影音</span>
                            </p>
                            <p class="app-download-line" style="display: none;">
                                <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&id=596814&pf=2&cg=CA8MTH1D1V1&sign=4de210208e97c709de7cbe7907e61f17&url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201206%2F12%2Forg.droidiris-100.apk"
                                    class="button-cmn button-s1">免费下载 </a>
                            </p>
                            <div class="box-app-detail">
                                <h2 class="f-s2">
                                    在线搜图</h2>
                                <h2 class="price-new c-orange f-bold">
                                    免费</h2>
                                <p class="m-t5 c-gray">
                                    一款在线搜索图片的应用，内置各家搜索引擎，搜索的图片以3D网格…
                                </p>
                                <p class="m-t5">
                                    <span class="fl-r c-gray">10088人推荐</span>
                                </p>
                                <p>
                                    <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 0%">
                                    </i></span><span class="vote-text c-gray">0.0</span>
                                </p>
                            </div>
                        </div>
                    </li>
                <?}?>
            </ul>
            <ul class="p-b15 t-c clearfix">
                <? for($i = 0; $i < 6; $i++){ ?>
                    <li class="li-hori-w122">
                        <div class="box-app">
                            <p>
                                <a href="http://m.163.com/android/software/316feo.html" class="img-app"><i class="img-app-none">
                                </i>
                                    <img src="http://img6.ph.126.net/YRM1keZGTYOZjZ-NRrIvQg==/1354457587949293196.png"
                                        width="70" height="70">
                                </a>
                            </p>
                            <h5 class="t-overflow m-t8">
                                <a href="http://m.163.com/android/software/316feo.html">传感音乐播放器</a></h5>
                            <p class="app-price-line">
                                <span class="price-new"><i></i>影音</span>
                            </p>
                            <p class="app-download-line" style="display: none;">
                                <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&id=1924312&pf=2&cg=CA8MTH1D1V1&sign=0e31a647d9db07b87bf9c3771e79392c&url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201205%2F03%2Fcom.zgui.musicshaker-54.apk"
                                    class="button-cmn button-s1">免费下载 </a>
                            </p>
                            <div class="box-app-detail">
                                <h2 class="f-s2">
                                    传感音乐播放器</h2>
                                <h2 class="price-new c-orange f-bold">
                                    免费</h2>
                                <p class="m-t5 c-gray">
                                    依靠四种体感模式就可快速换歌的音乐播放器。
                                </p>
                                <p class="m-t5">
                                    <span class="fl-r c-gray">86371人推荐</span>
                                </p>
                                <p>
                                    <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 73%">
                                    </i></span><span class="vote-text c-gray">7.3</span>
                                </p>
                            </div>
                        </div>
                    </li>
                <?}?>
            </ul>
        </div>
    </div>
    <div class="arti-ft">
        <div class="arti-ft-c">
            <div class="arti-ft-c-content">
            </div>
        </div>
        <span class="arti-ft-l"></span><span class="arti-ft-r"></span>
    </div>
</div>