<div class="arti">
    <div class="arti-hd arti-hd-bar">
        <div class="arti-hd-c">
            <div class="arti-hd-c-content">
                <h3 class="arti-hd-title">
                    <span class="ico-android">热门分类</span></h3>
            </div>
        </div>
        <span class="arti-hd-l"></span><span class="arti-hd-r"></span>
    </div>
    <div class="arti-bd">
        <div class="arti-bd-content">
            <div class="p-t30 p-b20 arti-bg-w240">
                <ul class="clearfix">
                   <?= $this->partial('index/android/hot_category.phtml', array('id'=>'102', 'name'=>'省钱利器', 'apps'=>$this->hotCategories[102])); ?>
                   <?= $this->partial('index/android/hot_category.phtml', array('id'=>'103', 'name'=>'美容护肤', 'apps'=>$this->hotCategories[103])); ?>
                   <?= $this->partial('index/android/hot_category.phtml', array('id'=>'104', 'name'=>'时尚阅读', 'apps'=>$this->hotCategories[104])); ?>
                </ul>
            </div>
            <div class="p-t30 p-b20 arti-bg-w240">
                <ul class="clearfix">
                    <?= $this->partial('index/android/hot_category.phtml', array('id'=>'105', 'name'=>'美食旅游', 'apps'=>$this->hotCategories[105])); ?>
                    <?= $this->partial('index/android/hot_category.phtml', array('id'=>'106', 'name'=>'影音娱乐', 'apps'=>$this->hotCategories[106])); ?>
                    <?= $this->partial('index/android/hot_category.phtml', array('id'=>'107', 'name'=>'便捷工具', 'apps'=>$this->hotCategories[107])); ?>
                </ul>
            </div>
        </div>
    </div>
    <div class="arti-ft">
        <div class="arti-ft-c">
            <div class="arti-ft-c-content">
            </div>
        </div>
        <span class="arti-ft-l"></span><span class="arti-ft-r"></span>
    </div>
</div>