<div class="sect-side">
    <div class="arti side-show-detail">
        <div class="arti-hd arti-hd-bar">
            <div class="arti-hd-c">
                <div class="arti-hd-c-content">
                    <h3 class="arti-hd-title">
                        <span class="ico-android"><?=$this->hot_name?></span></h3>
                </div>
            </div>
            <span class="arti-hd-l"></span><span class="arti-hd-r"></span>
        </div>
        <div class="arti-bd">
            <div class="arti-bd-content">
                <div class="m-h10">
                    <ol>
                        <?  $i = 0; 
                            foreach ($this->hot_apps as $app) {
                            $i++;
                            ?>
                        <li class="li-rank li-rank-first">
                            <div class="li-rank-hd">
                                <span class="li-rank-num"><i class="logo-num<?=$i?>"></i></span>
                                <h5 class="li-rank-title-s t-overflow">
                                    <a href="/android/app/<?=$app->id?>.html"><?=$app->name?></a></h5>
                            </div>
                            <div class="li-rank-bd li-rank-unfold" style="<?=$i==1?'':'display: none;'?>">
                                <div class="li-rank-text">
                                    <div class="li-rank-text-content">
                                        <p class="app-download-line p-t5">
                                            <a href="/download/<?=$app->id?>" class="btn-cmn btn-s1">免费下载</a>
                                        </p>
                                        <p class="m-t5 c-gray"><?=$app->category_name?></p>
                                        <p>
                                            <span class="vote-column">
                                                <i style="width: <?=$app->star?>%"></i>
                                            </span>
                                            <span class="vote-text c-gray"><?=$app->star/10?>
                                            </span>
                                        </p>
                                    </div>
                                </div>
                                <div class="li-rank-img">
                                    <a href="/android/app/<?=$app->id?>.html" class="img-app"><i class="img-app-none">
                                    </i>
                                        <img src="<?=$app->logo?>" width="70" height="70"></a>
                                </div>
                            </div>
                        </li>
                        <?}?>
                    </ol>
                </div>
            </div>
        </div>
        <div class="arti-ft">
            <div class="arti-ft-c">
                <div class="arti-ft-c-content">
                </div>
            </div>
            <span class="arti-ft-l"></span><span class="arti-ft-r"></span>
        </div>
    </div>
</div>