<div class="sect-side">
    <div class="arti side-show-detail" id="yui_3_4_0_4_1339546066975_1096">
        <div class="arti-hd arti-hd-bar">
            <div class="arti-hd-c">
                <div class="arti-hd-c-content">
                    <h3 class="arti-hd-title">
                        <span class="ico-android">热门游戏排行榜</span></h3>
                </div>
            </div>
            <span class="arti-hd-l"></span><span class="arti-hd-r"></span>
        </div>
        <div class="arti-bd" id="yui_3_4_0_4_1339546066975_1104">
            <div class="arti-bd-content" id="yui_3_4_0_4_1339546066975_1103">
                <div class="m-h10" id="yui_3_4_0_4_1339546066975_1102">
                    <ol id="yui_3_4_0_4_1339546066975_1101">
                        <li class="li-rank li-rank-first" id="yui_3_4_0_4_1339546066975_1100">
                            <div class="li-rank-hd">
                                <span class="li-rank-num"><i class="logo-num1"></i></span>
                                <h5 class="li-rank-title-s t-overflow">
                                    <a href="http://m.163.com/android/software/2vbrqf.html">会说话的汤姆猫</a></h5>
                            </div>
                            <div class="li-rank-bd li-rank-unfold" id="yui_3_4_0_4_1339546066975_1099" style="">
                                <div class="li-rank-text" id="yui_3_4_0_4_1339546066975_1098">
                                    <div class="li-rank-text-content" id="yui_3_4_0_4_1339546066975_1097">
                                        <p class="app-download-line p-t5">
                                            <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&id=3663&pf=2&cg=CA96B6HQND1&sign=e9bbc269fdc7802b12f208793aea6ed5&url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201111%2F13%2Fcom.outfit7.talkingtom_34.apk"
                                                class="btn-cmn btn-s1">免费下载</a></p>
                                        <p class="m-t5 c-gray" id="yui_3_4_0_4_1339546066975_1095">
                                            休闲益智</p>
                                        <p>
                                            <span class="vote-column"><i style="width: 87%"></i></span><span class="vote-text c-gray">
                                                8.7</span></p>
                                    </div>
                                </div>
                                <div class="li-rank-img">
                                    <a href="http://m.163.com/android/software/2vbrqf.html" class="img-app"><i class="img-app-none">
                                    </i>
                                        <img src="/upload/icon/28991922618645254.png"
                                            width="70" height="70"></a>
                                </div>
                            </div>
                        </li>
                        <? for($i = 2; $i <= 13; $i++){ ?>
                            <li class="li-rank">
                                <div class="li-rank-hd">
                                    <span class="li-rank-num"><i class="logo-num<?=$i?>"></i></span>
                                    <h5 class="li-rank-title-s t-overflow">
                                        <a href="http://m.163.com/android/software/2vdd03.html">会说话的狗狗</a></h5>
                                </div>
                                <div class="li-rank-bd" style="display: none;">
                                    <div class="li-rank-text">
                                        <div class="li-rank-text-content">
                                            <p class="app-download-line p-t5">
                                                <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&id=54019&pf=2&cg=CA96B6HQND1&sign=9482ed3cc2feefbf80cdfa80a2cf1e82&url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201203%2F16%2Fcom.outfit7.talkingben-8.apk"
                                                    class="btn-cmn btn-s1">免费下载</a></p>
                                            <p class="m-t5 c-gray">
                                                休闲益智</p>
                                            <p>
                                                <span class="vote-column"><i style="width: 81%"></i></span><span class="vote-text c-gray">
                                                    8.1</span></p>
                                        </div>
                                    </div>
                                    <div class="li-rank-img">
                                        <a href="http://m.163.com/android/software/2vdd03.html" class="img-app"><i class="img-app-none">
                                        </i>
                                            <img src="/upload/icon/28991922618645254.png"
                                                width="70" height="70"></a>
                                    </div>
                                </div>
                            </li>
                        <?}?>
                    </ol>
                </div>
            </div>
        </div>
        <div class="arti-ft">
            <div class="arti-ft-c">
                <div class="arti-ft-c-content">
                </div>
            </div>
            <span class="arti-ft-l"></span><span class="arti-ft-r"></span>
        </div>
    </div>
</div>