<div class="arti">
	<div class="arti-hd arti-hd-bar">
	    <div class="arti-hd-c">
	        <div class="arti-hd-c-content">
	            <h3 class="arti-hd-title">
	                <span class="ico-android">装机必备</span></h3>
	            <span class="arti-hd-more"><a class="a-s4" href="/android/install_recommend.html">
	                更多&gt;&gt;</a></span>
	        </div>
	    </div>
	    <span class="arti-hd-l"></span><span class="arti-hd-r"></span>
	</div>
	<div class="arti-bd">
	    <div class="arti-bd-content">
	        <ul class="p-v20 t-c clearfix">
	            <li class="li-hori-w122">
                    <div class="box-app">
                        <p>
                            <a href="/android/app/9.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/20120626112329492.png"
                                    width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/9.html">美丽说</a></h5>
                        <p class="app-price-line">
                            <span class="price-new"><i></i>美容护肤</span>
                        </p>
                        <p class="app-download-line" style="display: none;">
                            <a href="/download/9"
                                class="button-cmn button-s1">免费下载 </a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">
                                美丽说</h2>
                            <h2 class="price-new c-orange f-bold">
                                免费</h2>
                            <p class="m-t5 c-gray">
                                专为时尚女生量身定做的逛淘宝利器
                            </p>
                            <p class="m-t5">
                                <span class="fl-r c-gray">27804人推荐</span>
                            </p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 95%">
                                </i></span><span class="vote-text c-gray">0.0</span>
                            </p>
                        </div>
                    </div>
                </li>
                <li class="li-hori-w122">
                    <div class="box-app">
                        <p>
                            <a href="/android/app/10.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/20120627120254880.jpg"
                                    width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/10.html">美妆易购</a></h5>
                        <p class="app-price-line">
                            <span class="price-new"><i></i>省钱利器</span>
                        </p>
                        <p class="app-download-line" style="display: none;">
                            <a href="/download/10"
                                class="button-cmn button-s1">免费下载 </a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">
                                美妆易购</h2>
                            <h2 class="price-new c-orange f-bold">
                                免费</h2>
                            <p class="m-t5 c-gray">
                                最便捷的化妆品购物工具
                            </p>
                            <p class="m-t5">
                                <span class="fl-r c-gray">26890人推荐</span>
                            </p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 90%">
                                </i></span><span class="vote-text c-gray">0.0</span>
                            </p>
                        </div>
                    </div>
                </li>
	            <? for($i = 0; $i < 4; $i++){ ?>
	                <li class="li-hori-w122">
	                    <div class="box-app">
	                        <p>
	                            <a href="/android/app/1.html" class="img-app"><i class="img-app-none">
	                            </i>
	                                <img src="http://img6.ph.126.net/YRM1keZGTYOZjZ-NRrIvQg==/1354457587949293196.png"
	                                    width="70" height="70">
	                            </a>
	                        </p>
	                        <h5 class="t-overflow m-t8">
	                            <a href="http://m.163.com/android/software/31e75h.html">高速骑士</a></h5>
	                        <p class="app-price-line">
	                            <span class="price-new"><i></i>竞速游戏</span>
	                        </p>
	                        <p class="app-download-line" style="display: none;">
	                            <a href="/download/1"
	                                class="button-cmn button-s1">免费下载 </a>
	                        </p>
	                        <div class="box-app-detail">
	                            <h2 class="f-s2">
	                                高速骑士</h2>
	                            <h2 class="price-new c-orange f-bold">
	                                免费</h2>
	                            <p class="m-t5 c-gray">
	                                含有众多恶搞成分的竞速游戏。
	                            </p>
	                            <p class="m-t5">
	                                <span class="fl-r c-gray">27804人推荐</span>
	                            </p>
	                            <p>
	                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 0%">
	                                </i></span><span class="vote-text c-gray">0.0</span>
	                            </p>
	                        </div>
	                    </div>
	                </li>
	            <?}?>
	        </ul>
	        <ul class="p-b15 t-c clearfix">
	            <? for($i = 0; $i < 6; $i++){ ?>
	                <li class="li-hori-w122">
	                    <div class="box-app">
	                        <p>
	                            <a href="http://m.163.com/android/software/31akh5.html" class="img-app"><i class="img-app-none">
	                            </i>
	                                <img src="http://img6.ph.126.net/YRM1keZGTYOZjZ-NRrIvQg==/1354457587949293196.png"
	                                    width="70" height="70">
	                            </a>
	                        </p>
	                        <h5 class="t-overflow m-t8">
	                            <a href="http://m.163.com/android/software/31akh5.html">加菲食物保卫战</a></h5>
	                        <p class="app-price-line">
	                            <span class="price-new"><i></i>休闲益智</span>
	                        </p>
	                        <p class="app-download-line" style="display: none;">
	                            <a href="download/1"
	                                class="button-cmn button-s1">免费下载 </a>
	                        </p>
	                        <div class="box-app-detail">
	                            <h2 class="f-s2">
	                                加菲食物保卫战</h2>
	                            <h2 class="price-new c-orange f-bold">
	                                免费</h2>
	                            <p class="m-t5 c-gray">
	                                加菲猫主题塔防游戏，游戏性颇佳。
	                            </p>
	                            <p class="m-t5">
	                                <span class="fl-r c-gray">46177人推荐</span>
	                            </p>
	                            <p>
	                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 86%">
	                                </i></span><span class="vote-text c-gray">8.6</span>
	                            </p>
	                        </div>
	                    </div>
	                </li>
	            <?}?>
	        </ul>
	    </div>
	</div>
	<div class="arti-ft">
	    <div class="arti-ft-c">
	        <div class="arti-ft-c-content">
	        </div>
	    </div>
	    <span class="arti-ft-l"></span><span class="arti-ft-r"></span>
	</div>
</div>