<div class="arti">
	<div class="arti-hd arti-hd-bar">
	    <div class="arti-hd-c">
	        <div class="arti-hd-c-content">
	            <h3 class="arti-hd-title">
	                <span class="ico-android">装机必备</span></h3>
	            <span class="arti-hd-more"><a class="a-s4" href="/android/install_recommend.html">
	                更多&gt;&gt;</a></span>
	        </div>
	    </div>
	    <span class="arti-hd-l"></span><span class="arti-hd-r"></span>
	</div>
	<div class="arti-bd">
	    <div class="arti-bd-content">
	        <ul class="p-v20 t-c clearfix">
	            <li class="li-hori-w122">
                    <div class="box-app">
                        <p>
                            <a href="/android/app/9.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/20120626112329492.png"
                                    width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/9.html">美丽说</a></h5>
                        <p class="app-price-line">
                            <span class="price-new"><i></i>美容护肤</span>
                        </p>
                        <p class="app-download-line" style="display: none;">
                            <a href="/download/9"
                                class="button-cmn button-s1">免费下载 </a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">
                                美丽说</h2>
                            <h2 class="price-new c-orange f-bold">
                                免费</h2>
                            <p class="m-t5 c-gray">
                                专为时尚女生量身定做的逛淘宝利器
                            </p>
                            <p class="m-t5">
                                <span class="fl-r c-gray">27804人推荐</span>
                            </p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 95%">
                                </i></span><span class="vote-text c-gray">0.0</span>
                            </p>
                        </div>
                    </div>
                </li>
                <li class="li-hori-w122">
                    <div class="box-app">
                        <p>
                            <a href="/android/app/10.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/20120627120254880.jpg"
                                    width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/10.html">美妆易购</a></h5>
                        <p class="app-price-line">
                            <span class="price-new"><i></i>省钱利器</span>
                        </p>
                        <p class="app-download-line" style="display: none;">
                            <a href="/download/10"
                                class="button-cmn button-s1">免费下载 </a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">
                                美妆易购</h2>
                            <h2 class="price-new c-orange f-bold">
                                免费</h2>
                            <p class="m-t5 c-gray">
                                最便捷的化妆品购物工具
                            </p>
                            <p class="m-t5">
                                <span class="fl-r c-gray">26890人推荐</span>
                            </p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 90%">
                                </i></span><span class="vote-text c-gray">0.0</span>
                            </p>
                        </div>
                    </div>
                </li>
                <li class="li-hori-w122">
                    <div class="box-app">
                        <p>
                            <a href="/android/app/11.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/20120627114638465.jpg"
                                    width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/11.html">米格宝宝日记</a></h5>
                        <p class="app-price-line">
                            <span class="price-new"><i></i>便捷生活</span>
                        </p>
                        <p class="app-download-line" style="display: none;">
                            <a href="/download/11"
                                class="button-cmn button-s1">免费下载 </a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">
                                米格宝宝日记</h2>
                            <h2 class="price-new c-orange f-bold">
                                免费</h2>
                            <p class="m-t5 c-gray">
                                最好的宝宝成长记录工具
                            </p>
                            <p class="m-t5">
                                <span class="fl-r c-gray">26890人推荐</span>
                            </p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 90%">
                                </i></span><span class="vote-text c-gray">0.0</span>
                            </p>
                        </div>
                    </div>
                </li>
                <li class="li-hori-w122">
                    <div class="box-app">
                        <p>
                            <a href="/android/app/12.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/20120627124812581.png"
                                    width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/12.html">安卓壁纸</a></h5>
                        <p class="app-price-line">
                            <span class="price-new"><i></i>主题壁纸</span>
                        </p>
                        <p class="app-download-line" style="display: none;">
                            <a href="/download/12"
                                class="button-cmn button-s1">免费下载</a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">
                                安卓壁纸</h2>
                            <h2 class="price-new c-orange f-bold">
                                免费</h2>
                            <p class="m-t5 c-gray">
                                排名第一的手机美化软件，已拥有1000万用户
                            </p>
                            <p class="m-t5">
                                <span class="fl-r c-gray">34725人推荐</span>
                            </p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 90%">
                                </i></span><span class="vote-text c-gray">0.0</span>
                            </p>
                        </div>
                    </div>
                </li>
                <li class="li-hori-w122">
                    <div class="box-app">
                        <p>
                            <a href="/android/app/13.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/20120627125858667.png"
                                    width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/13.html">虾米音乐</a></h5>
                        <p class="app-price-line">
                            <span class="price-new"><i></i>影音娱乐</span>
                        </p>
                        <p class="app-download-line" style="display: none;">
                            <a href="/download/13"
                                class="button-cmn button-s1">免费下载</a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">
                                虾米音乐</h2>
                            <h2 class="price-new c-orange f-bold">
                                免费</h2>
                            <p class="m-t5 c-gray">
                                虾米网为Android操作系统量身打造的免费音乐应用
                            </p>
                            <p class="m-t5">
                                <span class="fl-r c-gray">24026人推荐</span>
                            </p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 90%">
                                </i></span><span class="vote-text c-gray">0.0</span>
                            </p>
                        </div>
                    </div>
                </li>
                <li class="li-hori-w122">
                    <div class="box-app">
                        <p>
                            <a href="/android/app/14.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/20120627011622106.png"
                                    width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/14.html">奇艺高清影视</a></h5>
                        <p class="app-price-line">
                            <span class="price-new"><i></i>影音娱乐</span>
                        </p>
                        <p class="app-download-line" style="display: none;">
                            <a href="/download/14"
                                class="button-cmn button-s1">免费下载</a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">
                                奇艺高清影视</h2>
                            <h2 class="price-new c-orange f-bold">
                                免费</h2>
                            <p class="m-t5 c-gray">
                                奇艺高清影视是百度旗下高清视频客户端
                            </p>
                            <p class="m-t5">
                                <span class="fl-r c-gray">36029人推荐</span>
                            </p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 90%">
                                </i></span><span class="vote-text c-gray">0.0</span>
                            </p>
                        </div>
                    </div>
                </li>
            </ul>
	        <ul class="p-b15 t-c clearfix">
	            <li class="li-hori-w122">
	            	<div class="box-app">
                        <p>
                            <a href="/android/app/15.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/20120627083121776.jpg"
                                    width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/15.html">QQ游戏大厅</a></h5>
                        <p class="app-price-line">
                            <span class="price-new"><i></i>棋牌游戏</span>
                        </p>
                        <p class="app-download-line" style="display: none;">
                            <a href="/download/15"
                                class="button-cmn button-s1">免费下载</a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">
                                QQ游戏大厅</h2>
                            <h2 class="price-new c-orange f-bold">
                                免费</h2>
                            <p class="m-t5 c-gray">
                                手机QQ游戏大厅Android客户端
                            </p>
                            <p class="m-t5">
                                <span class="fl-r c-gray">46029人推荐</span>
                            </p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 90%">
                                </i></span><span class="vote-text c-gray">0.0</span>
                            </p>
                        </div>
                    </div>
                </li>
                <li class="li-hori-w122">
	            	<div class="box-app">
                        <p>
                            <a href="/android/app/16.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/201206270845164.jpg"
                                    width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/16.html">墨迹天气</a></h5>
                        <p class="app-price-line">
                            <span class="price-new"><i></i>装机必备</span>
                        </p>
                        <p class="app-download-line" style="display: none;">
                            <a href="/download/16"
                                class="button-cmn button-s1">免费下载</a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">
                                墨迹天气</h2>
                            <h2 class="price-new c-orange f-bold">
                                免费</h2>
                            <p class="m-t5 c-gray">
                                一款功能丰富，界面绚丽的天气预报生活软件产品
                            </p>
                            <p class="m-t5">
                                <span class="fl-r c-gray">26029人推荐</span>
                            </p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 90%">
                                </i></span><span class="vote-text c-gray">0.0</span>
                            </p>
                        </div>
                    </div>
                </li>
                <li class="li-hori-w122">
	            	<div class="box-app">
                        <p>
                            <a href="/android/app/17.html" class="img-app"><i class="img-app-none">
                            </i>
                                <img src="/upload/android/imgs/20120627085740211.png"
                                    width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8">
                            <a href="/android/app/17.html">未接来电记录</a></h5>
                        <p class="app-price-line">
                            <span class="price-new"><i></i>装机必备</span>
                        </p>
                        <p class="app-download-line" style="display: none;">
                            <a href="/download/17"
                                class="button-cmn button-s1">免费下载</a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2">未接来电记录</h2>
                            <h2 class="price-new c-orange f-bold">
                                免费</h2>
                            <p class="m-t5 c-gray">
                                电话记录拦截轻松搞定
                            </p>
                            <p class="m-t5">
                                <span class="fl-r c-gray">35029人推荐</span>
                            </p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 80%">
                                </i></span><span class="vote-text c-gray">0.0</span>
                            </p>
                        </div>
                    </div>
                </li>
                <li class="li-hori-w122">
					<div class="box-app" id="yui_3_4_0_3_1340815349186_164">
				        <p>
				            <a href="/android/app/18.html" class="img-app"><i class="img-app-none">
				            </i>
				                <img src="/upload/android/imgs/20120627102612448.jpg" width="70" height="70">
				            </a>
				        </p>
				        <h5 class="t-overflow m-t8">
				            <a href="/android/app/18.html">美图贴贴</a></h5>
				        <p class="app-price-line" style="display: none; ">
				            <span class="price-new"><i></i>影音娱乐</span>
				        </p>
				        <p class="app-download-line" style="">
				            <a href="/download/18" class="button-cmn button-s1">免费下载</a>
				        </p>
				        <div class="box-app-detail">
				            <h2 class="f-s2">美图贴贴</h2>
				            <h2 class="price-new c-orange f-bold">免费</h2>
				            <p class="m-t5 c-gray">一款专为女生设计的大头贴软件</p>
				            <p class="m-t5"><span class="fl-r c-gray">35029人推荐</span></p>
				            <p>
				                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 90%">
				                </i></span><span class="vote-text c-gray">0.0</span>
				            </p>
				        </div>
				    </div>
				</li>
				<li class="li-hori-w122">
					<div class="box-app">
				        <p>
				            <a href="/android/app/19.html" class="img-app"><i class="img-app-none">
				            </i>
				                <img src="/upload/android/imgs/20120627094933487.png" width="70" height="70">
				            </a>
				        </p>
				        <h5 class="t-overflow m-t8">
				            <a href="/android/app/19.html">卡卡记账</a></h5>
				        <p class="app-price-line" style="display: none; ">
				            <span class="price-new"><i></i>省钱利器</span>
				        </p>
				        <p class="app-download-line" style="">
				            <a href="/download/19" class="button-cmn button-s1">免费下载</a>
				        </p>
				        <div class="box-app-detail">
				            <h2 class="f-s2">卡卡记账</h2>
				            <h2 class="price-new c-orange f-bold">免费</h2>
				            <p class="m-t5 c-gray">方便实用的记账，管理银行卡的综合理财软件</p>
				            <p class="m-t5"><span class="fl-r c-gray">35029人推荐</span></p>
				            <p>
				                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 90%">
				                </i></span><span class="vote-text c-gray">0.0</span>
				            </p>
				        </div>
				    </div>
				</li>
	        </ul>
	    </div>
	</div>
	<div class="arti-ft">
	    <div class="arti-ft-c">
	        <div class="arti-ft-c-content">
	        </div>
	    </div>
	    <span class="arti-ft-l"></span><span class="arti-ft-r"></span>
	</div>
</div>