<div class="arti">
    <div class="arti-hd arti-hd-bar">
        <div class="arti-hd-c">
            <div class="arti-hd-c-content">
                <h3 class="arti-hd-title">
                    <span class="ico-android">新品推荐</span></h3>
                <span class="arti-hd-more"><a class="a-s4" href="/android/new_recommend.html">更多&gt;&gt;</a></span>
            </div>
        </div>
        <span class="arti-hd-l"></span><span class="arti-hd-r"></span>
    </div>
    <div class="arti-bd">
        <div class="arti-bd-content">
            <ul class="p-v20 t-c clearfix">
                <? for($i = 0; $i < 6; $i++){ ?>
                    <li class="li-hori-w122">
                        <div class="box-app" id="yui_3_4_0_4_1339548940557_11709">
                            <p>
                                <a href="/android/software/31di3f.html" class="img-app"><i class="img-app-none"></i>
                                    <img src="http://img8.ph.126.net/Jyox1mFK7FLo3P7WrmyZ0g==/613333974270136518.png"
                                        width="70" height="70">
                                </a>
                            </p>
                            <h5 class="t-overflow m-t8">
                                <a href="/android/software/31di3f.html">欢乐欧洲杯</a></h5>
                            <p class="app-price-line" style="">
                                <span class="price-new"><i></i>体育游戏</span>
                            </p>
                            <p class="app-download-line" style="display: none;">
                                <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&amp;id=2156399&amp;pf=2&amp;cg=CA96B6I1VH1&amp;sign=d47aa26399b6c2f3825b46cb8a161110&amp;url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201206%2F11%2Fourcup.apk"
                                    class="button-cmn button-s1">免费下载 </a>
                            </p>
                            <div class="box-app-detail">
                                <h2 class="f-s2">
                                    欢乐欧洲杯</h2>
                                <h2 class="price-new c-orange f-bold">
                                    免费</h2>
                                <p class="m-t5 c-gray">
                                    安卓平台最好玩的欧洲杯主题社交竞猜游戏 欢乐欧洲杯是android …
                                </p>
                                <p class="m-t5">
                                    <span class="fl-r c-gray">2747人推荐</span>
                                </p>
                                <p>
                                    <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 100%">
                                    </i></span><span class="vote-text c-gray">10.0</span>
                                </p>
                            </div>
                        </div>
                    </li>
                <?}?>
            </ul>
            <ul class="p-b15 t-c clearfix">
                <? for($i = 0; $i < 6; $i++){ ?>
                    <li class="li-hori-w122">
                        <div class="box-app" id="yui_3_4_0_4_1339548940557_1730">
                            <p>
                                <a href="/android/software/314t4i.html" class="img-app"><i class="img-app-none"></i>
                                    <img src="http://img0.ph.126.net/0sKqCUXIg75-_-A0FL3biQ==/2504282867811887400.png"
                                        width="70" height="70">
                                </a>
                            </p>
                            <h5 class="t-overflow m-t8">
                                <a href="/android/software/314t4i.html">七星滚球</a></h5>
                            <p class="app-price-line" style="">
                                <span class="price-new"><i></i>体育游戏</span>
                            </p>
                            <p class="app-download-line" style="display: none;">
                                <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&amp;id=1872786&amp;pf=2&amp;cg=CA96B6I1VH1&amp;sign=787a48fa1c99ed7e293eb2e17a0664a0&amp;url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201203%2F27%2Fcom.IdealBall-25.apk"
                                    class="button-cmn button-s1">免费下载 </a>
                            </p>
                            <div class="box-app-detail">
                                <h2 class="f-s2">
                                    七星滚球</h2>
                                <h2 class="price-new c-orange f-bold">
                                    免费</h2>
                                <p class="m-t5 c-gray">
                                    画面和配乐都充满中国风的滚珠游戏。
                                </p>
                                <p class="m-t5">
                                    <span class="fl-r c-gray">215500人推荐</span>
                                </p>
                                <p>
                                    <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 73%">
                                    </i></span><span class="vote-text c-gray">7.3</span>
                                </p>
                            </div>
                        </div>
                    </li>
                <?}?>
            </ul>
        </div>
    </div>
    <div class="arti-ft">
        <div class="arti-ft-c">
            <div class="arti-ft-c-content">
            </div>
        </div>
        <span class="arti-ft-l"></span><span class="arti-ft-r"></span>
    </div>
</div>