<div class="arti">
    <div class="arti-hd arti-hd-bar">
        <div class="arti-hd-c">
            <div class="arti-hd-c-content">
                <h3 class="arti-hd-title">
                    <span class="ico-android"><?=$this->recommendName?></span></h3>
                <span class="arti-hd-more"><a class="a-s4" href="/android/<?=$this->recommendType?>_recommend.html">更多&gt;&gt;</a></span>
            </div>
        </div>
        <span class="arti-hd-l"></span><span class="arti-hd-r"></span>
    </div>
    <div class="arti-bd">
        <div class="arti-bd-content">
            <ul class="p-v20 t-c clearfix">
                <?foreach ($this->apps as $app) {?>
                <li class="li-hori-w122">
                    <div class="box-app">
                        <p>
                            <a href="/android/app/<?=$app->id?>.html" class="img-app"><i class="img-app-none"></i><img src="<?=$app->logo?>" width="70" height="70">
                            </a>
                        </p>
                        <h5 class="t-overflow m-t8"><a href="/android/app/<?=$app->id?>.html"><?=$app->name?></a></h5>
                        <p class="app-price-line"><span class="price-new"><i></i><?=$app->category_name?></span></p>
                        <p class="app-download-line" style="display: none;">
                            <a href="/download/<?=$app->id?>" class="button-cmn button-s1">免费下载</a>
                        </p>
                        <div class="box-app-detail">
                            <h2 class="f-s2"><?=$app->name?></h2>
                            <h2 class="price-new c-orange f-bold">免费</h2>
                            <p class="m-t5 c-gray"><?=$app->comment?></p>
                            <p class="m-t5"><span class="fl-r c-gray"><?=$app->download_times?>人下载</span></p>
                            <p>
                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: <?=$app->star?>%">
                                </i></span><span class="vote-text c-gray"><?=$app->star/20?></span>
                            </p>
                        </div>
                    </div>
                </li>
                <?}?>
            </ul>
        </div>
    </div>
    <div class="arti-ft">
        <div class="arti-ft-c">
            <div class="arti-ft-c-content">
            </div>
        </div>
        <span class="arti-ft-l"></span><span class="arti-ft-r"></span>
    </div>
</div>