<div class="arti">
    <div class="arti-hd arti-hd-bar">
        <div class="arti-hd-c">
            <div class="arti-hd-c-content">
                <h3 class="arti-hd-title">
                    <span class="ico-android">热门分类</span></h3>
            </div>
        </div>
        <span class="arti-hd-l"></span><span class="arti-hd-r"></span>
    </div>
    <div class="arti-bd">
        <div class="arti-bd-content">
            <div class="p-t30 p-b20 arti-bg-w240">
                <ul class="clearfix">
                    <? $topics = array("省钱利器","美容护肤", "时尚阅读"); ?>
                    <? foreach ($topics as $topic) { ?>
                        <li class="li-hori-w240">
                            <div class="m-h15">
                                <p class="t-c">
                                    <a href="http://m.163.com/android/category/ca8mth20dq/index.html" class="btn-cat"
                                        target="_self"><?= $topic ?></a></p>
                                <ol class="m-t25 list-category-top">
                                    <?php for($i=0;$i<6;$i++) {?>
                                        <li class="li-rank-first" id="yui_3_4_0_4_1339547997667_1027">
                                            <div class="li-rank-hd">
                                                <span class="li-rank-thumb"><a href="http://m.163.com/android/software/30rvnt.html"
                                                    class="img-app-s"><i class="img-app-s-none"></i>
                                                    <img src="http://img8.ph.126.net/hhQpgsn2q8jtyrO8ltQYeQ==/2793639143870788368.png"
                                                        width="30" height="30"></a></span>
                                                <h5 class="li-rank-title t-overflow">
                                                    <a href="http://m.163.com/android/software/30rvnt.html">糗事百科</a></h5>
                                                <span class="li-rank-desc-s" style=""><span class="c-gray">&gt;100W人推荐</span></span>
                                                <div class="li-rank-download" style="display: none;">
                                                    <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&amp;id=1580541&amp;pf=2&amp;cg=CA8MTH20DQ1&amp;sign=877e5df6c6f6717a6a0daffe03fef988&amp;url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201205%2F22%2Fqiushibaike.apk"
                                                        class="button-cmn button-s1">免费下载 </a>
                                                </div>
                                            </div>
                                        </li>
                                    <?}?>
                                </ol>
                            </div>
                        </li>
                    <?}?>
                </ul>
            </div>
            <div class="p-t30 p-b20 arti-bg-w240">
                <ul class="clearfix">
                    <? $topics = array("美食旅游","摄影电影", "手机防毒"); ?>
                    <? foreach ($topics as $topic) { ?>
                        <li class="li-hori-w240">
                            <div class="m-h15">
                                <p class="t-c">
                                    <a href="http://m.163.com/android/category/ca8mth20dq/index.html" class="btn-cat"
                                        target="_self"><?= $topic ?></a></p>
                                <ol class="m-t25 list-category-top">
                                    <?php for($i=0;$i<6;$i++) {?>
                                        <li class="li-rank-first" id="yui_3_4_0_4_1339547997667_1027">
                                            <div class="li-rank-hd">
                                                <span class="li-rank-thumb"><a href="http://m.163.com/android/software/30rvnt.html"
                                                    class="img-app-s"><i class="img-app-s-none"></i>
                                                    <img src="http://img8.ph.126.net/hhQpgsn2q8jtyrO8ltQYeQ==/2793639143870788368.png"
                                                        width="30" height="30"></a></span>
                                                <h5 class="li-rank-title t-overflow">
                                                    <a href="http://m.163.com/android/software/30rvnt.html">糗事百科</a></h5>
                                                <span class="li-rank-desc-s" style=""><span class="c-gray">&gt;100W人推荐</span></span>
                                                <div class="li-rank-download" style="display: none;">
                                                    <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&amp;id=1580541&amp;pf=2&amp;cg=CA8MTH20DQ1&amp;sign=877e5df6c6f6717a6a0daffe03fef988&amp;url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201205%2F22%2Fqiushibaike.apk"
                                                        class="button-cmn button-s1">免费下载 </a>
                                                </div>
                                            </div>
                                        </li>
                                    <?}?>
                                </ol>
                            </div>
                        </li>
                    <?}?>
                </ul>
            </div>
            <div>
                <div class="p-v20 t-c">
                    <a href="javascript:void(0);" class="button-cmn button-s3" id="A1" target="_self"><span
                        class="icon-arrow">查看全部分类</span></a></div>
            </div>
        </div>
    </div>
    <div class="arti-ft">
        <div class="arti-ft-c">
            <div class="arti-ft-c-content">
            </div>
        </div>
        <span class="arti-ft-l"></span><span class="arti-ft-r"></span>
    </div>
</div>