<div class="arti">
	<div class="arti-hd arti-hd-bar">
	    <div class="arti-hd-c">
	        <div class="arti-hd-c-content">
	            <h3 class="arti-hd-title">
	                <span class="ico-android">装机必备</span></h3>
	            <span class="arti-hd-more"><a class="a-s4" href="http://m.163.com/android/game_recommend.html">
	                更多&gt;&gt;</a></span>
	        </div>
	    </div>
	    <span class="arti-hd-l"></span><span class="arti-hd-r"></span>
	</div>
	<div class="arti-bd">
	    <div class="arti-bd-content">
	        <ul class="p-v20 t-c clearfix">
	            <? for($i = 0; $i < 6; $i++){ ?>
	                <li class="li-hori-w122">
	                    <div class="box-app">
	                        <p>
	                            <a href="/android/app/1.html" class="img-app"><i class="img-app-none">
	                            </i>
	                                <img src="http://img6.ph.126.net/YRM1keZGTYOZjZ-NRrIvQg==/1354457587949293196.png"
	                                    width="70" height="70">
	                            </a>
	                        </p>
	                        <h5 class="t-overflow m-t8">
	                            <a href="http://m.163.com/android/software/31e75h.html">高速骑士</a></h5>
	                        <p class="app-price-line">
	                            <span class="price-new"><i></i>竞速游戏</span>
	                        </p>
	                        <p class="app-download-line" style="display: none;">
	                            <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&id=2177969&pf=2&cg=CA96B6ICJ11&sign=cbed28e08664b10a929da33cfeda2f62&url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201206%2F11%2Fcom.batteryacid.highwayrider-1.apk"
	                                class="button-cmn button-s1">免费下载 </a>
	                        </p>
	                        <div class="box-app-detail">
	                            <h2 class="f-s2">
	                                高速骑士</h2>
	                            <h2 class="price-new c-orange f-bold">
	                                免费</h2>
	                            <p class="m-t5 c-gray">
	                                含有众多恶搞成分的竞速游戏。
	                            </p>
	                            <p class="m-t5">
	                                <span class="fl-r c-gray">27804人推荐</span>
	                            </p>
	                            <p>
	                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 0%">
	                                </i></span><span class="vote-text c-gray">0.0</span>
	                            </p>
	                        </div>
	                    </div>
	                </li>
	            <?}?>
	        </ul>
	        <ul class="p-b15 t-c clearfix">
	            <? for($i = 0; $i < 6; $i++){ ?>
	                <li class="li-hori-w122">
	                    <div class="box-app">
	                        <p>
	                            <a href="http://m.163.com/android/software/31akh5.html" class="img-app"><i class="img-app-none">
	                            </i>
	                                <img src="http://img6.ph.126.net/YRM1keZGTYOZjZ-NRrIvQg==/1354457587949293196.png"
	                                    width="70" height="70">
	                            </a>
	                        </p>
	                        <h5 class="t-overflow m-t8">
	                            <a href="http://m.163.com/android/software/31akh5.html">加菲食物保卫战</a></h5>
	                        <p class="app-price-line">
	                            <span class="price-new"><i></i>休闲益智</span>
	                        </p>
	                        <p class="app-download-line" style="display: none;">
	                            <a href="http://analytics.163.com/ntes_dwld?prod=3gmarket&id=2060581&pf=2&cg=CA96B6HQND1&sign=c7f69d2d42edfcd7d66786cc042f3e90&url=http%3A%2F%2Ffile.m.163.com%2Fapp%2Ffree%2F201206%2F11%2Fcom.webprancer.google.garfieldDefense-2.apk"
	                                class="button-cmn button-s1">免费下载 </a>
	                        </p>
	                        <div class="box-app-detail">
	                            <h2 class="f-s2">
	                                加菲食物保卫战</h2>
	                            <h2 class="price-new c-orange f-bold">
	                                免费</h2>
	                            <p class="m-t5 c-gray">
	                                加菲猫主题塔防游戏，游戏性颇佳。
	                            </p>
	                            <p class="m-t5">
	                                <span class="fl-r c-gray">46177人推荐</span>
	                            </p>
	                            <p>
	                                <span class="vote-text c-orange"></span><span class="vote-column"><i style="width: 86%">
	                                </i></span><span class="vote-text c-gray">8.6</span>
	                            </p>
	                        </div>
	                    </div>
	                </li>
	            <?}?>
	        </ul>
	    </div>
	</div>
	<div class="arti-ft">
	    <div class="arti-ft-c">
	        <div class="arti-ft-c-content">
	        </div>
	    </div>
	    <span class="arti-ft-l"></span><span class="arti-ft-r"></span>
	</div>
</div>