<form enctype="multipart/form-data" action="" method="POST">
	<table>
		<tr>
			<td>应用ICON</td>
			<td><input type="file" name="appLogo"/></td>
		</tr>
		<tr>
			<td>应用程序</td>
			<td><input type="file" name="appPath"/></td>
		</tr>
		<tr>
			<td>图片1</td>
			<td><input type="file" name="appImgs[]"/></td>
		</tr>
		<tr>
			<td>图片2</td>
			<td><input type="file" name="appImgs[]"/></td>
		</tr>
		<tr>
			<td>图片3</td>
			<td><input type="file" name="appImgs[]"/></td>
		</tr>
		<tr>
			<td>图片4</td>
			<td><input type="file" name="appImgs[]"/></td>
		</tr>
		<tr>
			<td>图片5</td>
			<td><input type="file" name="appImgs[]"/></td>
		</tr>
		<tr>
			<td>图片6</td>
			<td><input type="file" name="appImgs[]"/></td>
		</tr>
		<tr>
			<td colspan="2"><input type="submit" value="Submit"></input></td>
		</tr>
	</table>
</form>