<form enctype="multipart/form-data" action="" method="post">   
	<table>
		<tr>
			<td>选择文件</td>
			<td><input name="uploadFile" type="file"></td>
		</tr>
		<tr>
			<td>应用类型</td>
			<td>
				<select name="appType">
					<option value="android">android</option>
					<option value="iphone">iphone</option>
				</select>
			</td>
		</tr>
		<tr>
			<td colsolespan="2"><input type="submit" value="上传文件"></td>
		</tr>
	</table>	   
</form>  