<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<?php echo $this->headTitle(); ?>
	<link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">

	<style type="text/css">
.header-b {
height: 88px;
width: 968px;
background: url(http://img4.cache.netease.com/apps/v2/img/sp1.jpg) no-repeat 0 -660px;
position: relative;
z-index: 1;
}
.nav-main {
position: absolute;
left: 0;
top: 0;
}
.nav-sub {
position: absolute;
top: 47px;
left: 0;
}
.nav-sub-li-first {
background: none;
}
.nav-sub-li {
float: left;
padding-left: 14px;
background: url(http://img4.cache.netease.com/apps/v2/img/sp1.jpg) no-repeat -800px -160px;
}
.nav-sub-item-current:visited, .nav-sub-item-current:hover, .nav-sub-item-last-current:visited, .nav-sub-item-current:hover {
color: #2B2B2B;
}
.nav-sub-item:visited, .nav-sub-item:hover {
color: white;
text-decoration: none;
}
.header-search {
position: absolute;
top: 46px;
right: 13px;
}
	</style>
</head>
<body>
	<div class="header-b">
                    <div class="nav-main">
                        <a href="/iphone/index.html" class="nav-main-item nav-main-item-1 " target="_self">iPhone</a>
						<a href="/ipad/index.html" class="nav-main-item nav-main-item-2 " target="_blank">iPad</a>
                        <a href="/android/index.html" class="nav-main-item nav-main-item-3  nav-main-item-current " target="_self">Android</a>
                        <a href="/s60v3/index.html" class="nav-main-item nav-main-item-4 " target="_self">塞班 V3</a>
                        <a href="/s60v5/index.html" class="nav-main-item nav-main-item-5 " target="_self">塞班 V5</a>
                        <a href="/java/index.html" class="nav-main-item nav-main-item-6 " target="_self">Java</a>
                    </div>
				
							
                    <div class="nav-sub">
                        <ul>
															<li class="nav-sub-li nav-sub-li-first"><a href="/android/index.html" class="nav-sub-item  nav-sub-item-current  " target="_self"><span>首页</span></a></li>
							
																					
							<li class="nav-sub-li">
								<a href="#game" target="_self" class="nav-sub-item" id="apps-game-trigger"><span><i></i>游戏</span></a>
							</li>
							
														
															
							<li class="nav-sub-li">
									<a href="#app" target="_self" class="nav-sub-item" id="apps-app-trigger"><span><i></i>
																		应用
									</span>
								</a>
							</li>
														
							
							                                <li class="nav-sub-li"><a href="/android/subject/list@all.html" class="nav-sub-item " target="_self"><span>专题</span></a></li>
														
							<li class="nav-sub-li">
															<a href="/android/top.html" class="nav-sub-item " target="_self">
									<span>排行</span>
								</a>
														
							</li>														                            
                        </ul>
                    </div>
											<div class="header-search">
                                <form method="get" target="_self" action="/search/multiform">
                                    <input type="hidden" name="platform" value="2">
                                    <span class="bg-form-cmn bg-form-s2"><input type="text" placeholder="请输入应用名" class="input-s5" id="app-search-input" name="query"></span>
                                    <input type="submit" class="button-cmn button-s2" value=" ">
                                </form>
						</div>
										
				</div>

	<?php echo $this->layout()->content; ?>
</body>
</html>
