<div class="sect m-t10">
    <div class="sect-main">
        <div class="yui3-tabs-transition-fade yui3-widget yui3-tabs"
            style="">
            <div class="slide yui3-tabs-content" id="apps-slide">
                <div class="slide-main">
                    <div class="yui3-tabs-panel" style="">
                        <a href="ipad/software/31bi5d.html">
                            <img alt="大餐时间到(Munch Time Lite)" width="735" height="210" src="http://img6.cache.netease.com/m/app/201206/11/9S251S78.jpg"></a>
                    </div>
                    <div class="yui3-tabs-panel" style="">
                        <a href="/android/software/2vu9ds.html" id="yui_3_4_0_4_1339546066975_2184">
                            <img alt="粘粘世界(World Of Goo)" width="735" height="210" src="http://img6.cache.netease.com/m/app/201206/11/9S251S78.jpg"></a>
                    </div>
                    <div class="yui3-tabs-panel yui3-tabs-panel-selected" style="opacity: 1;">
                        <a href="/android/software/30s04b.html">
                            <img alt="三重镇(Triple Town)" width="735" height="210" src="http://img6.cache.netease.com/m/app/201206/13/9S8292CO.png"></a>
                    </div>
                </div>
                <ul class="slide-side">
                    <li class="yui3-tabs-trigger"><span></span></li>
                    <li class="yui3-tabs-trigger"><span></span></li>
                    <li class="yui3-tabs-trigger yui3-tabs-trigger-selected"><span></span></li>
                </ul>
                <span class="slide-corner-r"></span><span class="slide-corner-l">
                </span>
            </div>
        </div>
    </div>
    <div class="sect-side">
        <div class="m-b10 free-ad">
            <a href="http://m.163.com/mobileapp/">
                <img src="http://img4.cache.netease.com/m/app/201204/06/9MOU511O.png" width="210"
                    height="100">
            </a>
        </div>
        <div class="free-ad">
            <a href="http://m.163.com/android/special/2vbo81.html">
                <img src="http://img4.cache.netease.com/m/app/201204/06/9MOU511O.png" width="210"
                    height="100">
            </a>
        </div>
    </div>
</div>