<div class="sect m-t10">
    <div class="sect-main">
        <div class="yui3-tabs-transition-fade yui3-widget yui3-tabs"
            style="">
            <div class="slide yui3-tabs-content" id="apps-slide">
                <div class="slide-main">
                    <div class="yui3-tabs-panel yui3-tabs-panel-selected" style="">
                        <a href="/android/app/57.html">
                            <img alt="腾讯手机管家" width="735" height="210" src="/upload/imgs/20120702145442.jpg"></a>
                    </div>
                    <div class="yui3-tabs-panel" style="">
                        <a href="/android/app/10.html">
                            <img alt="美妆易购" width="735" height="210" src="/upload/imgs/20120802205806.jpg"></a>
                    </div>
                    <div class="yui3-tabs-panel" style="opacity: 1;">
                        <a href="/android/app/66.html">
                            <img alt="新浪微博" width="735" height="210" src="/upload/imgs/20120611092521.jpg"></a>
                    </div>
                </div>
                <ul class="slide-side">
                    <li class="yui3-tabs-trigger yui3-tabs-trigger-selected"><span></span></li>
                    <li class="yui3-tabs-trigger"><span></span></li>
                    <li class="yui3-tabs-trigger"><span></span></li>
                </ul>
                <span class="slide-corner-r"></span><span class="slide-corner-l">
                </span>
            </div>
        </div>
    </div>
    <div class="sect-side">
        <div class="m-b10 free-ad">
            <a href="/android/install_recommend.html">
                <img src="/upload/imgs/20120709233425.png" width="210"
                    height="100">
            </a>
        </div>
        <div class="free-ad">
            <a href="/android/game_recommend.html">
                <img src="/upload/imgs/20120711215512.png" width="210"
                    height="100">
            </a>
        </div>
    </div>
</div>