<script type="text/javascript" src="/js/bootstrap.min.js"></script>
<script type="text/javascript">
	$(function(){
		$('.carousel').carousel();
	})
</script>

<div class="content-box2">
	<div class="column-w">
		<div class="ad-650">
			<div id="adtp" class="look-ad-img-grp" style="width: 4550px; left: -3250px; ">
			</div>
			<div id="myCarousel" class="carousel slide">
				<div class="carousel-inner">
				<div class="active item">
					<a href="http://www.anfone.com/soft/30216.html" target="_blank"><img src="http://r.anfone.com/upload/advertise/1337241480463.jpg"></a>
				</div>
				<div class="item">
					<a href="http://www.anfone.com/soft/30216.html" target="_blank"><img src="http://r.anfone.com/upload/advertise/1337241480463.jpg"></a></div>
				<div class="item">
					<a href="http://anfone.com/soft/27450.html" target="_blank"><img src="http://r.anfone.com/upload/advertise/1332900607176.jpg"></a></div>
				</div>
				<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
				<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
				</div>
		</div>
		<div style="padding:10px;">
			<a href="/soft/appinfo.html"><img src="http://img4.cache.netease.com/m/app/201204/06/9MOU4PLP.png" width="210" height="100"></a>
		</div>
		<div style="padding:10px;">
			<a href="/soft/appinfo.html"><img src="http://img4.cache.netease.com/m/app/201204/06/9MOU511O.png" width="210" height="100"></a>
		</div>
		<div class="clear"></div>
	</div>
</div>