<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- saved from url=(0025)http://m.163.com/android/ -->
<html xmlns="http://www.w3.org/1999/xhtml" class="yui3-js-enabled">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="Keywords" content="安卓游戏,安卓软件,安卓系统,安卓游戏下载,安卓,android">
    <meta name="Description" content="安卓游戏软件下载、安卓工具下载。包括安卓手机游戏、安卓3D游戏、安卓手机应用、安卓刷机工具、安卓铃声壁纸等应用下载。">
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7">
    <link href="/css/style.css" rel="stylesheet" type="text/css">
    <link href="/css/adp_1.4.1.1.css" type="text/css" rel="stylesheet">
    <link rel="shortcut icon" href="http://www.163.com/favicon.ico">
    <link type="text/css" rel="stylesheet" href="/js/combo" charset="utf-8">
    <link type="text/css" rel="stylesheet" href="/js/combo(3)" charset="utf-8">

    <script src="/js/yui-min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/js/combo(1)" charset="utf-8"></script>
    <script type="text/javascript" src="/js/combo(2)" charset="utf-8"></script>
    <script type="text/javascript" src="/js/ntes-overlay-trigger.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/combo(4)" charset="utf-8"></script>
    <script type="text/javascript" src="/js/ntes-placeholder.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/combo(5)" charset="utf-8"></script>
    <script type="text/javascript" src="/js/combo(6)" charset="utf-8"></script>
    <script type="text/javascript" src="/js/ntes-tabs.js" charset="utf-8"></script>

    <!--<base target="_blank">-->
    <title>安卓(Android)游戏[软件]_安卓游戏、安卓软件、安卓客户端官网免费下载</title>
</head>
<body>
    <div class="wrap">
        <?php echo $this->partial('header.phtml'); ?>
        <?php echo $this->partial('ads.phtml'); ?>
        <?php echo $this->layout()->content; ?>
        <?php echo $this->partial('footer.phtml'); ?>
    </div>

</body>
</head>