<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- saved from url=(0025)http://m.163.com/android/ -->
<html xmlns="http://www.w3.org/1999/xhtml" class="yui3-js-enabled">
<head> 		
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7">
    <meta name="Keywords" content="愤怒的小鸟夏日版">
    <meta name="Description" content="愤怒的小鸟夏日版">

    <link href="/css/style.css" rel="stylesheet" type="text/css"> 
    <link href="/css/adp_1.4.1.1.css" type="text/css" rel="stylesheet">
    <link href="/css/tie.css" rel="stylesheet" type="text/css">

    <script type="text/javascript" src="/js/jquery1.7.2.min.js" charset="utf-8"></script>
    <script src="/js/main.js" type="text/javascript"></script>

    <script src="/js/yui-min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/js/combo(1)" charset="utf-8"></script>
    <script type="text/javascript" src="/js/combo(2)" charset="utf-8"></script>
    <script type="text/javascript" src="/js/ntes-overlay-trigger.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/combo(4)" charset="utf-8"></script>
    <script type="text/javascript" src="/js/combo(5)" charset="utf-8"></script>

<title>Android首页_网易应用中心</title>
</head>
<body>
    <div class="wrap">
        <?php echo $this->partial('header.phtml'); ?>
        <?php echo $this->partial('ads.phtml'); ?>
        <?php echo $this->layout()->content; ?>
        <?php echo $this->partial('footer.phtml'); ?>
    </div>

    <script type="text/javascript">
        $(".tabs-2-list .yui3-tabs-trigger").click(function(){
            $(".tabs-2-list .yui3-tabs-trigger").removeClass("yui3-tabs-trigger-selected");
            $(this).addClass("yui3-tabs-trigger-selected");
            $(".arti-s-bd .yui3-tabs-panel").removeClass("yui3-tabs-panel-selected");
            if($(this).html() == "简介")
            {
               $(".arti-s-bd .yui3-tabs-panel:first").addClass("yui3-tabs-panel-selected");    
            }
            else
            {
                $(".arti-s-bd .yui3-tabs-panel:last").addClass("yui3-tabs-panel-selected");   
            }
        })
    </script>
</body>
</head>