<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- saved from url=(0025)http://m.163.com/android/ -->
<html xmlns="http://www.w3.org/1999/xhtml" class="yui3-js-enabled">
<head> 		
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7">
    <meta name="Keywords" content="愤怒的小鸟夏日版">
    <meta name="Description" content="愤怒的小鸟夏日版">

    <link href="/css/style.css" rel="stylesheet" type="text/css"> 
    <link href="/css/adp_1.4.1.1.css" type="text/css" rel="stylesheet">
    <link href="/css/tie.css" rel="stylesheet" type="text/css">

    <script src="/js/yui-min.js" type="text/javascript"></script>
    <script src="http://wandoujia.com/api/wdapi.js" type="text/javascript"></script>
    <script type="text/javascript" src="/js/comments_1.4.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/image-list_1.3.js" charset="utf-8"></script>
    <script type="text/javascript" src="/js/image-viewer_1.3.js" charset="utf-8"></script>
<title>愤怒的小鸟夏日版(Angry Birds Seasons)_休闲益智_Android首页_网易应用中心</title>
</head>
<body>
    <div class="wrap">
        <?php echo $this->partial('header.phtml'); ?>
        <?php echo $this->partial('ads.phtml'); ?>
        <?php echo $this->layout()->content; ?>
        <?php echo $this->partial('footer.phtml'); ?>
    </div>

</body>
</head>