<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- saved from url=(0025)http://m.163.com/android/ -->
<html xmlns="http://www.w3.org/1999/xhtml" class="yui3-js-enabled">
<head> 		
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7">
    <meta name="Keywords" content="<?=$this->app->meta_keyword?>,美眉应用,美眉应用中心,美眉应用市场,手机应用,应用平台,应用市场,手机游戏,手机游戏下载,手机应用下载,android,market,apk,安智,安卓,安致">
    <meta name="Description" content="<?=$this->app->meta_desc?>,美眉应用,美眉应用中心,美眉应用市场,手机应用">

    <link href="/css/style.css" rel="stylesheet" type="text/css"> 
    <link href="/css/adp_1.4.1.1.css" type="text/css" rel="stylesheet">
    <link href="/css/tie.css" rel="stylesheet" type="text/css">

    <script type="text/javascript" src="/js/jquery1.7.2.min.js" charset="utf-8"></script>
    <script src="/js/main.js" type="text/javascript"></script>
    <script src="http://www.google-analytics.com/ga.js" type="text/javascript"></script>

<title><?=$this->app->name?>_美眉应用中心</title>
</head>
<body>
    <div class="wrap">
        <?php echo $this->partial('header.phtml'); ?>
        <?php echo $this->partial('ads.phtml'); ?>
        <?php echo $this->layout()->content; ?>
        <?php echo $this->partial('footer.phtml'); ?>
    </div>
</body>
</head>