    <div class="bnav m-t15">
        <h1>友情链接</h1>
        <ul class="links">
            <li><a href="http://www.lady8844.com" title="爱美网" target="_blank"><img height="31" width="88" src="/upload/imgs/lnk_lady8844.jpg"></a></li>
            <li><a href="http://bbs.aili.com" title="爱丽时尚社区" target="_blank"><img height="31" width="88" src="/upload/imgs/lnk_aili.jpg"></a></li>
            <li><a href="#" title="三开" target="_blank"><img height="31" width="88" src="http://r.anfone.com/upload/1338878466422.jpg"></a></li>
            <li><a href="#" title="优机网" target="_blank"><img height="31" width="88" src="http://r.anfone.com/upload/1338254464332.png"></a></li>
            <li><a href="#" title="蜡笔同步" target="_blank"><img height="31" width="88" src="http://r.anfone.com/upload/1334650433935.png"></a></li>
            <li><a href="#" title="苹果小站" target="_blank"><img height="31" width="88" src="http://r.anfone.com/upload/1333678295059.png"></a></li>
            <li><a href="#" title="卡卡西游MO" target="_blank"><img height="31" width="88" src="http://r.anfone.com/upload/1333098812348.jpg"></a></li>
        </ul>
    </div>

    <div class="m-t15 footer">
        <a href="#" target="_blank">首页</a> - <a href="#" target="_blank">关于我们</a> - <a href="#" target="_blank">帮助中心</a> - <a href="#" target="_blank">意见反馈</a><br>
        Copyright (c) mmapp.me All rights reserved.
    </div>

    <div class="float-menu" id="go_top" style="visibility: visible;">
        <p class="m-t5">
            <a href="javascript:void(0);" class="btn-to-top m-t1" id="btn-to-top">回顶部</a></p>
    </div>
    
    <style>
    .bnav h1
    {
    	
    }
    .bnav .links li
    {
    	display: list-item;
margin: 0 7px 10px 10px;
width: 88px;
height: 31px;
line-height: 31px;
text-align: center;
float: left;
background: #F4F4F4;
    }
    </style>