    <div class="bnav m-t15">
        <h1>友情链接</h1>
        <ul class="links">
            <li><a href="/soft/soft!fLink?id=55" title="APP游戏部落" target="_blank"><img height="31" width="88" src="http://r.anfone.com/upload/1336543259507.jpg"></a></li>
            <li><a href="/soft/soft!fLink?id=1" title="讯飞语音云论坛" target="_blank"><img height="31" width="88" src="http://www.anfone.com/images/xfyyy.png"></a></li>
            <li><a href="/soft/soft!fLink?id=58" title="三开" target="_blank"><img height="31" width="88" src="http://r.anfone.com/upload/1338878466422.jpg"></a></li>
            <li><a href="/soft/soft!fLink?id=56" title="优机网" target="_blank"><img height="31" width="88" src="http://r.anfone.com/upload/1338254464332.png"></a></li>
            <li><a href="/soft/soft!fLink?id=54" title="蜡笔同步" target="_blank"><img height="31" width="88" src="http://r.anfone.com/upload/1334650433935.png"></a></li>
            <li><a href="/soft/soft!fLink?id=53" title="苹果小站" target="_blank"><img height="31" width="88" src="http://r.anfone.com/upload/1333678295059.png"></a></li>
            <li><a href="/soft/soft!fLink?id=52" title="卡卡西游MO" target="_blank"><img height="31" width="88" src="http://r.anfone.com/upload/1333098812348.jpg"></a></li>
        </ul>
    </div>

    <div class="m-t15 footer">
        <a href="#" target="_blank">首页</a> - <a href="#" target="_blank">关于我们</a> - <a href="#" target="_blank">帮助中心</a> - <a href="#" target="_blank">意见反馈</a><br>
        Copyright (c) mmapp.me All rights reserved.
    </div>
    <!-- end: footer -->
    <!-- float menu -->
    <div class="float-menu" id="float-menu" style="visibility: visible;">
        <p class="m-t5">
            <a href="javascript:void(0);" class="btn-to-top m-t1" id="btn-to-top">回顶部</a></p>
    </div>
    <!-- START NetEase Devilfish 2006 -->

    <script src="/js/ntes.js" type="text/javascript"></script>

    <script type="text/javascript">
        _ntes_nacc = "mobile";
        neteaseTracker();
                    </script>

    <!-- END NetEase Devilfish 2006 -->

    <script src="/js/header_1.4.1.1.js"
        type="text/javascript"></script>

    <script src="/js/float-menu.js"
        type="text/javascript"></script>

    <!-- START NetEase Devilfish 2006 -->

    <script src="/js/ntes.js" type="text/javascript"></script>

    <script type="text/javascript">
        _ntes_nacc = "mobile";
        neteaseTracker();
            </script>

    <!-- END NetEase Devilfish 2006 -->

    <script src="/js/home-android.js"
        type="text/javascript"></script>


    <style>
    .bnav h1
    {
    	
    }
    .bnav .links li
    {
    	display: list-item;
margin: 0 7px 10px 10px;
width: 88px;
height: 31px;
line-height: 31px;
text-align: center;
float: left;
background: #F4F4F4;
    }
    </style>