    <div class="header">
        <div class="header-c">
            <div class="logo-header">
                <i></i><a href="/" target="_self">美眉应用</a>
            </div>
        </div>
        <div class="header-b">
            <div class="nav-main">
                <a href="/android.html" class="nav-main-item nav-main-item-1 <?=$this->app_class=='Android'?'nav-main-item-current':''?> " target="_self">Android</a>
                <a href="/iphone.html" class="nav-main-item nav-main-item-2 <?=$this->app_class=='iPhone'?'nav-main-item-current':''?>" target="_self">iPhone</a> 
            </div>
            <div class="nav-sub">
                <ul>
                    <li class="nav-sub-li nav-sub-li-first">
                        <a href="/android.html" class="nav-sub-item <?=$this->nav_name==''?'nav-sub-item-current':'' ?>" target="_self"><span>首页</span></a>
                    </li>
                    <li class="nav-sub-li">
                        <a href="/android/game.html" target="_self" class="nav-sub-item <?=$this->nav_name=='游戏'?'nav-sub-item-current':'' ?>"><span>游戏</span></a> 
                    </li>
                    <li class="nav-sub-li">
                        <a href="/android/app.html" target="_self" class="nav-sub-item <?=$this->nav_name=='应用'?'nav-sub-item-current':'' ?>"><span>应用</span></a>
                    </li>
                    <li class="nav-sub-li">
                        <a href="/android/subject.html" class="nav-sub-item <?=$this->nav_name=='专题'?'nav-sub-item-current':'' ?>" target="_self"><span>专题</span></a>
                    </li>
                    <li class="nav-sub-li">
                        <a href="/android/top.html" class="nav-sub-item <?=$this->nav_name=='排行'?'nav-sub-item-current':'' ?>" target="_self"><span>排行</span> </a>
                    </li>
                </ul>
            </div>
            <div class="header-search">
                <form method="get" target="_self" action="/search">
                    <input type="hidden" name="platform" value="2">
                    <span class="bg-form-cmn bg-form-s2">
                        <input type="text" placeholder="请输入应用名" class="input-s5 yui3-aclist-input" id="app-search-input" name="wd" aria-autocomplete="list" aria-expanded="false" role="combobox" autocomplete="off">
                        <div class="yui3-widget yui3-aclist yui3-widget-positioned yui3-aclist-hidden"
                        style="position: absolute; width: 245px; left: 0px; top: 25px;" aria-hidden="true">
                            <div class="yui3-aclist-content">
                                <ul class="yui3-aclist-list" role="listbox">
                                </ul>
                            </div>
                        </div>
                        <div class="yui3-aclist-aria" aria-live="polite" role="status">
                        </div>
                    </span>
                    <input type="submit" class="button-cmn button-s2" value=" ">
                </form>
            </div>
        </div>
    </div>
</div>