<div class="sect m-t15">
    <div class="sect-main">
        <!--装机必备-->
        <?php echo $this->partial('index/android/install.phtml'); ?>
        <div class="arti m-t15">
        </div>
        <!--游戏推荐-->
        <?php echo $this->partial('index/android/game.phtml'); ?>
    </div>
        <?php echo $this->partial('index/android/hot_game.phtml', array('games'=>$this->games)); ?>
</div>
<div class="sect m-t15">
    <div class="sect-main">
        <?php echo $this->partial('index/android/new.phtml'); ?>
        <div class="arti m-t15"></div>
        <?php echo $this->partial('index/android/hot_category.phtml'); ?>
    </div>
    <?php echo $this->partial('index/android/hot_app.phtml'); ?>
</div>